### ISSUE TITLE
FEATURE REQUEST - Open the notification when the icon is pressed

### ISSUE THREAD

**Issue by smeagol152** [peterhajas/MobileNotifier#10]
To open the notification you have to tab the notification and press the OPEN button. It would be very quickly is you pressed ths program icon from the notification to open the notification.

**Comment by robvx** [comment]
I was also expecting that action after using GriP for Notified Pro for so long. I'm tired of how buggy the status bar gets with Notified Pro's drop down menu. I'm hoping this becomes a viable replacement. I love GriP's collapsable popups though, at half size you can still interact with navigation buttons in apps when it is set to cover the status bar.
