### ISSUE TITLE
LockInfo & MobileNotifier Notifications Non-Responsive

### ISSUE THREAD

**Issue by genesanchez** [peterhajas/MobileNotifier#101]
Love MobileNotifier, But for some reason, now that I have upgraded to the newest beta, the Notifications Bar on the lockscreen is nonresponsive?  I have tried every way I can think of to get it to respond. So what I have to do is unlock the iPhone 4, double tap the home button then access the alerts from there? I believe is has something to do with LockInfo and I have also reported to him as well.

**Comment by DanweR** [comment]
Same problems! This isn't convenient. may be somehow pop-up notications on lockscreen can be enabled?

**Comment by DanweR** [comment]
Hey! Use Activator! i used it for opening a dashboard on the lockscreen! i assigned for doubletap on a clock a dashBoard!!! you should aslo try! easy way to access your msges

**Comment by genesanchez** [comment]
gosh, that's a great idea. but my luck is not with me.  I just did as you said and nothing activates?  I am going to try and restart my iPhone to see if that fixes it.
