### ISSUE TITLE
beta3r6: Screen notification when the phone is lock not working

### ISSUE THREAD

**Issue by bullishpip** [peterhajas/MobileNotifier#107]
With the phone locked, the screen notification is not displaying. The phone will light up and vibrate and/or play audio notification but the lock screen will not show the MobileNotifier count. If I unlock the phone and then go back to the lock screen the MobileNotifer count will be present.

Issue happening on VZW iPhone iOS build 4.2.6

**Comment by nickv2002** [comment]
I have the exact same problem.

I'm running MobileNotifer version 0.3.7-2 on the AT&T iPhone 4 with iOS 4.2.1.
