### ISSUE TITLE
beta3r6: SMS notification while the phone is locked has no body

### ISSUE THREAD

**Issue by bullishpip** [peterhajas/MobileNotifier#108]
SMS notification while the phone is locked comes across weird. The SMS address or contact of the person is correct but the body of the SMS message is replaced with the word 'Text'

Issue happening on VZW iPhone iOS build 4.2.6

**Comment by adamjford** [comment]
I'm having the same issue. It sucks having to unlock my phone to just check the message.

**Comment by BeauGiles** [comment]
I'm still having this with Beta 4.
I get a new SMS, but all I see is who it's from and 'Text' as the body.
