### ISSUE TITLE
Disable

### ISSUE THREAD

**Issue by 9Life42** [peterhajas/MobileNotifier#109]
I'd love to have the option to disable MobileNotifier. There are simply times when I want to return to the built in notification system and it would be nice to be able to do this without uninstalling the whole thing.

**Comment by peterhajas** [comment]
Why not uninstall the tweak to disable it? Under what circumstances do you want to disable it?

**Comment by 9Life42** [comment]
I am always trying new extensions and sometimes they conflict with already installed ones. I love it when here is a simple switch to disable functionality without having to go into cydia and respring multiple times. This isn't a vital feature, but for someone like me it can be convenient when trying to make the phone work the way I want.

**Comment by scalamanderr** [comment]
I would like to second this idea. I like to try different combinations, and a simple on off switch would suffice.

**Comment by timnovinger** [comment]
This feature is not planned. Simply uninstall the tweak if you no longer want it in place.
