### ISSUE TITLE
BUG: AlertDashboard stays open at lock screen after sleep

### ISSUE THREAD

**Issue by robvx** [peterhajas/MobileNotifier#11]
When you open the AlertDashboard and leave it there when the phone goes to sleep the AlertDashboard will still be open on the lock screen.

Im also having an issue where the phone does not wake on alerts anymore but that may be some sort of conflict with "popup blocker" even though it is set to wake on alert

**Comment by peterhajas** [comment]
Thanks for this! I've fixed this issue:

https://github.com/peterhajas/MobileNotifier/commit/797e3a8e7b176737785ea6221f1bb8607127c76c

and it'll be in a forthcoming release. Thanks!
