### ISSUE TITLE
Pop-up During Call is obscured

### ISSUE THREAD

**Issue by btaroli** [peterhajas/MobileNotifier#110]
The green bar at the top of the display -- when not in Phone app during a call -- partially obscures MN pop-ups that occur in this state. MN may need to recognize this situation to adjust pop-up location, as apps are advised of reduced screen space and shorten accordingly.

**Comment by peterhajas** [comment]
Do you still encounter this issue on beta4?

**Comment by btaroli** [comment]
I'll have to test to be certain. I have noticed the new behavior and that apps resize underneath the pop-up. Very nice. I'll make a definitive test of this behavior to see how it does now.

**Comment by btaroli** [comment]
Yes, the pop-up overlap issue _is_ resolved. :-)
