### ISSUE TITLE
Glitchy Lockscreen

### ISSUE THREAD

**Issue by ipodlover77** [peterhajas/MobileNotifier#111]
Love the program but had to uninstall for a couple of flaws.

The lock screen unfortunately is not consistent. When the first message comes in, nothing shows up. The screen lights up to let u know a message came but other than that, it shows you nothing. No name, no message, no mobile notifier lock screen, just the default lock screen with the wallpaper. When you than turn the screen off and turn it back on, the name of the person who texted comes up, but no mobile notifier still. You have to manually turn on the screen, unlock the phone, than relock it for the mobile notifier lock screen to come alive. Once its up, new messages will come in and do a live update so im guessing the very first message is the one that always gets it wonky. 

Another issue is, when you go into the message app, your mobile notifier badges will still persist. The only way to get rid of them is to bring up that pull down menu and manually select clear.

And the last issue is the sound, but thats already been covered.

The thing that makes it unusable is the first issue. I love how mobile notifiers work, so i figured i would sacrifice the lock screen by going into the settings and disabling "lock screen" so i could have it like the original iphone way but still have the slick system for when the phones unlocked but nope, still has the same glitch. even when the lockscreen is disabled, new messages will come in, but won't show up. The screen will only light up, but nothing else. 

Hope the new beta gets everything sorted out. This has so much potential.

using an iphone 4 on 4.3.1

**Comment by peterhajas** [comment]
I'm a little confused here, you appear to be describing three issues in one Issue submission. Can you break these up?
