### ISSUE TITLE
Notifications Only w/o AlertDashboard

### ISSUE THREAD

**Issue by sjmorrow** [peterhajas/MobileNotifier#114]
I love MobileNotifier, but also love LockInfo. Having notification history integrated into LockInfo with all my other phone information is awesome. So iI think it would be nice to have a sort of "MobileNotifier Lite" that only replaces apple's annoying pop-ups with the notifications in MobileNotifier, but does not keep track of the notification history. I suppose I could just not use your AlertDashboard, but I would rather not have that extra overhead running on my phone keeping track of notifications if I am not going to use it. Just an idea, but thanks for all yall's hard work on this project, it's awesome.

**Comment by peterhajas** [comment]
There is minimal overhead with regards to alert storage, so if you'd like to not use MobileNotifier's dashboard, you do not need to be concerned.

Since this is not an issue with the product, I will close this issue.
