### ISSUE TITLE
Multiple Selectable Themes

### ISSUE THREAD

**Issue by Appstache** [peterhajas/MobileNotifier#116]
I'm not saying Kyle's doing a bad job, just that some people are going to not use an app because they don't like how it looks. A simple way to combat this is to have an option in Settings to change the look of MobileNotifier, that way you could have multiple styles ("Apple Default"), Regular, White, etc. and people could pick from that list.

Example second style: http://i56.tinypic.com/1zno9ea.jpg

Ignoring the technical inaccuracies of the above photo, you get what I'm suggesting.

**Comment by timnovinger** [comment]
Simple feature to choose between light and dark notification styles was added in [this commit](https://github.com/peterhajas/MobileNotifier/commit/a6189573078975d21b9d3b3e5d7713f8755bb84a).
