### ISSUE TITLE
Contact SMS Tones not Honoured

### ISSUE THREAD

**Issue by BeauGiles** [peterhajas/MobileNotifier#118]
I'm reporting this here, as it only occurred after I installed MobileNotifier.
I have custom SMS tones set up for some contacts (for example, Tri-Tone for SMSes from Twitter) to help identify which ones I should be paying attention to. I notice that after installing MobileNotifier, these no longer seem to be honoured; Twitter SMS now have the same tone as my selected tone for everyone 'Calypso'.

**Comment by r0hit** [comment]
+1

**Comment by btaroli** [comment]
I think the latest beta resolves this issue.

**Comment by orendan** [comment]
I see this behavior in beta5.

**Comment by BeauGiles** [comment]
@skupendous so it's even worse than it was before? At least I had 'Calypso' play for all my SMSes, even though I should've had Tri-tone for SMSes from 'Twitter'. I haven't had MobileNotifier installed since I reported this.

However I notice that other plugins are having problems; for example, Notified Pro when combined with the Notified Bar (latest beta for both) and notifications blocked, custom SMS tones per contacts aren't honoured either. Only the default tone is played.

Is anyone able to at least work around this until it is fixed (if ever) in MobileNotifier? Eg, Vibrafications can set custom tones per contact among other things....

**Comment by BeauGiles** [comment]
The 'Comment & Close' and 'Comment' buttons are too close to each other when you're in a hurry ;-)
I can confirm that custom default SMS tones (and therefore custom contact tones) aren't honoured; tritone is played no matter what.

**Comment by kavehv** [comment]
+1, hope this can be fixed soon

**Comment by timnovinger** [comment]
This was fixed in [this commit](https://github.com/peterhajas/MobileNotifier/commit/9bde7db0e336aa7d5d83a1232eda6d9b49aef7b8).
