### ISSUE TITLE
beta4 still has duplicate sounds

### ISSUE THREAD

**Issue by scalamanderr** [peterhajas/MobileNotifier#120]
I still get my default sms tone plus the default tritone when receiving a text..

also was the bitesms quick reply feature merged into this release?

**Comment by heliomass** [comment]
I have to second this. The built in tri-tone seems superfluous considering apps have their own push notification sound. Is there the possibility of having an off option for this, as for me (and perhaps others too) it's intrusive enough to be a deal breaker.

**Comment by peterhajas** [comment]
Currently working on this issue - I'll keep you guys updated.

**Comment by btaroli** [comment]
I haven't been paying close enough attention to this just yet. If it's still proving to be a challenge, I'd agree that potentially having an option to disable MN's sound would be nice.

**Comment by btaroli** [comment]
This is odd... seems that only MN's sound is playing now. :-(

**Comment by btaroli** [comment]
After a few tests, seems to vary... sometimes I hear both, sometimes I hear only MN. Testing with SMS and IM (Beejive).

**Comment by scalamanderr** [comment]
Just to let you know I'm using biteSMS and when I go to open the notification it opens the messages app, is there a way to get around this?

**Comment by timnovinger** [comment]
@scalamanderr, Please open a separate issue for your biteSMS/opening a notification issue that you're reporting here. It will get lost otherwise. Thanks.

**Comment by peterhajas** [comment]
This has been fixed - https://github.com/peterhajas/MobileNotifier/issues/72 - thanks for reporting it!

**Comment by TaylorMonkey-duplicate** [comment]
This still doesn't appear to be fixed in Beta 5.  Both the tri-tone and the tone selected for SMS messages in settings will play.  MobileNotifier should simply not play any sound and let the actual push notifications handle sounds themselves.
