### ISSUE TITLE
Antique lockscreen doesnt work

### ISSUE THREAD

**Issue by zeronullempty** [peterhajas/MobileNotifier#122]
I use slantedlock a html lockscreen tgeme and every time i get texted on textfree or meassaged on kik i dont get a notification.. Screen just powers on and i just see my lockscreen. Pleaae fix.

Using : ipod 4g, 4.1

**Comment by Neblinio** [comment]
I'm also having this issue. I want to use Apple's native notifications on lockscreen, but nothing appears when I disable Lockscreen view. Enabling Antique Lock Alerts has no effect at all.

iPhone 4 with iOS 4.3.2

**Comment by zeronullempty** [comment]
Good o know im not the only one

**Comment by zeronullempty** [comment]
All we need now is hajas

**Comment by XeNoW** [comment]
Same here. One of the reasons why I disabled MobileNotifier. I Need the native notifications on lockscreen.

**Comment by zeronullempty** [comment]
OK

**Comment by zeronullempty** [comment]
sorry for closing
