### ISSUE TITLE
Feature request: more lines or "more" button on alert

### ISSUE THREAD

**Issue by jojo3632** [peterhajas/MobileNotifier#124]
This is a great tool. But however annoying the built in iOS pop up messages are, they show the full message for SMS or new updates. Can we have a way to view the full message with Mobile Notifier ? A few suggestions: being able to swipe to scroll the text or the addition of a third button to expand the alert box to view the full message?

Thanks,
Jordan.

**Comment by btaroli** [comment]
I recall there were issues logged previously related to the desire to have more lines (or just the full message) display when the pop-up was tapped... like having it expand vertically when the "later" and "open" buttons are displayed. I wholeheartedly support this request, as I too have been plagued by the question of whether to open or not. Sometimes the first 10 or 20 characters is enough, sometimes not. Being able to see the full message when tapping on the alert would be extremely helpful in this regard.

**Comment by JasonWSnoW** [comment]
Could it be an added functionality like Mail is in the settings? Idk how hard it would be to re-implement the same code but it could give us a vertical preview of 3,4, or 5 lines based on what we chose in the settings menu. Just an idea.

**Comment by snum** [comment]
This would be a great idea. This would help in instances where an app alerts you of something, but when you open the alert it doesn't not bring you to the original alert itself (e.g., someone favorites one of your tweets and Echofon pushes that it was fav'd, MN only displays a few char's of the alert, but selecting the alert only opens Echofon).

**Comment by timnovinger** [comment]
Feature added in later builds.
