### ISSUE TITLE
Keyboard Hidden on Lock Screen

### ISSUE THREAD

**Issue by jedicraft** [peterhajas/MobileNotifier#125]
when the notifications are visible on the lock screen and you slide to unlock, the keyboard comes up under the notifications. Its probably better if the keyboard comes on top

**Comment by jedicraft** [comment]
I have a screenshot, is there any way to attach?

**Comment by pocketlim** [comment]
Hey Jedicraft, didn't realize you already opened this. I'll move my bug info down here too (related bug https://github.com/peterhajas/MobileNotifier/issues/130) 

## Here's the original:

Hey Peter, once again, great work on beta4!

In the Lockscreen, when you open the preview, it gets covered when you slide to unlock if you have a lock code. I believe the preview should get hidden once you slide.

Here's pre slide: http://dl.dropbox.com/u/10514579/preSlide.png

Here's post slide: http://dl.dropbox.com/u/10514579/postSlide.png

Notice how the preview hides the keys. Just a small change. Hopefully you can somehow detect the slide/unlock. If not then if there's way to detect a touch ouside of the preview window so you can hide it.

**Comment by timnovinger** [comment]
This issue is a duplicate, and has been [fixed and closed](https://github.com/peterhajas/MobileNotifier/issues/130).
