### ISSUE TITLE
Springboard Crash - Delete Items in Lockscreen's AlertDashboard

### ISSUE THREAD

**Issue by tinifni** [peterhajas/MobileNotifier#126]
Here are the steps to reproduce the crash:
1. Start on **Lockscreen** with missed notifications present
2. Tap **Missed Notifications** to bring up the **Lockscreen's AlertDashboard**
3. Slide from left to right over a missed item to reveal **Delete** button
4. Delete item
5. Unlock phone
6. Activate **AlertDashboard** (by bringing up Apple's application switcher menu or otherwise)
7. Slide from left to right on the item deleted in Steps 3-4 to reveal **Delete** button (previously deleted item is still present)
8. Delete item

After Step 8, the Springboard crashes.

iPhone 3GS
iOS 4.2.1
MobileNotifier beta4, Decadent DinoBites

**Comment by timnovinger** [comment]
This issue was fixed by @peterhajas in the following commits:
- https://github.com/peterhajas/MobileNotifier/commit/3caa3bce4b7b601c57776d39a964af7c6cb8840d
- https://github.com/peterhajas/MobileNotifier/commit/a3b400dbcfaf5b7e72b84358d2cb64dbad4bb366

Great bug report @tinifni!
