### ISSUE TITLE
No more slide-to-dismiss on pop-up?

### ISSUE THREAD

**Issue by btaroli** [peterhajas/MobileNotifier#128]
I really got to enjoy slide-to-dismiss. It doesn't seem to work in beta4. I can't decide if it bothers me or not, but now that the pop-up causes app area to scale, I guess it's less intrusive. Though it does overlay the regular status bar. Not sure, but I think I'd like swipe-to-dismiss to stay... Am I crazy?

**Comment by nandreetta** [comment]
You're not crazy at all. The auto-hide isn't bad, but I still miss the swipe. I'm not sure if it would conflict with SBSettings' swipe gesture now that alerts live in the status bar.

**Comment by snum** [comment]
I miss this too. Swiping is easier than tapping a clicking "Later" or maybe I'm just lazy. :/

**Comment by peterhajas** [comment]
I'm looking into this - I think it has to do with the status bar alert style...

**Comment by timnovinger** [comment]
Yes this functionality has been removed. We're currently looking into other uses for user swiping of notifications in the status bar area.

**Comment by timnovinger** [comment]
This issue is now outdated due to the recent changes with swiping notifications.
