### ISSUE TITLE
Dashboard/Task Switcher display transparency too high

### ISSUE THREAD

**Issue by pocketlim** [peterhajas/MobileNotifier#129]
Hey Peter, great work on beta4! I'm still waiting for a donation link so I can send you $$. 

The new dashboard in Beta4 created a transparent background, which is lovely on dark screens. 

Screenshot Dark: http://dl.dropbox.com/u/10514579/dark.png

However, on light backgrounds, it doesn't look particularly good. The dashboard block is not cleanly separated from the content behind it, and the Clear pending action is almost hidden.

Screenshot Light: http://dl.dropbox.com/u/10514579/light.png

Just wanted to bring this to your attention.

**Comment by btaroli** [comment]
I agree... I would term this "please decrease transparency on task switcher display". I have found it troublesome in the region there the "clear" tap area is.

**Comment by peterhajas** [comment]
This has been fixed - thanks for reporting it!

**Comment by pocketlim** [comment]
Awesome! Thank you for fixing it! :D

**Comment by jojo3632** [comment]
I was going to ask for the opposite :-(
I have a dark them. I miss the nice darkened background on the taskswitcher. 
Can we have the ability to adjust the transparency of the dash on switcher?
