### ISSUE TITLE
3 notifications on springboard with no messages

### ISSUE THREAD

**Issue by ghost** [peterhajas/MobileNotifier#13]
my springboard is showing that I have 3 notifications, but I have already read and replied to the text messages it claims I still have.

**Comment by peterhajas** [comment]
Do they show up in the AlertDashboard?

**Comment by ghost** [comment]
my apologies, I meant my lockscreen, not springboard

**Comment by ghost** [comment]
can I email you some screenshots?

**Comment by peterhajas** [comment]
Yep! Sure. If they're in the AlertDashboard, then they still exist, and they'll still show up on the lockscreen.

**Comment by ghost** [comment]
what address can I email?

**Comment by peterhajas** [comment]
peterhajas@gmail.com
