### ISSUE TITLE
Lockscreen preview covers keys after unlock if you have a passcode

### ISSUE THREAD

**Issue by pocketlim** [peterhajas/MobileNotifier#130]
Hey Peter, once again, great work on beta4! 

In the Lockscreen, when you open the preview, it gets covered when you slide to unlock if you have a lock code. I believe the preview should get hidden once you slide. 

Here's pre slide: http://dl.dropbox.com/u/10514579/preSlide.png

Here's post slide: http://dl.dropbox.com/u/10514579/postSlide.png

Notice how the preview hides the keys. Just a small change. Hopefully you can somehow detect the slide/unlock. If not then if there's way to detect a touch ouside of the preview window so you can hide it.

**Comment by timnovinger** [comment]
This issue has been fixed in the following commits:
- https://github.com/peterhajas/MobileNotifier/commit/77a48a588919ad6e897ebb5755e1bce863eb83de
- https://github.com/peterhajas/MobileNotifier/commit/111dac92ce5a7284ea9d36de99b78d3a98f98edc

Thanks for the great bug report @pocketlim!
