### ISSUE TITLE
Locktopus Compatibility

### ISSUE THREAD

**Issue by r0hit** [peterhajas/MobileNotifier#132]
I'm using locktopus to password-protect my messages. When a notification comes and I click open, it takes me directly to the message without asking the password. Could it be possible to integrate MobileNotifier with Locktopus?

**Comment by timnovinger** [comment]
Sorry, support for Locktopus is not planned.

**Comment by r0hit** [comment]
oh alright.. thanks for the clarification. great work on beta 5 :)
