### ISSUE TITLE
Feature Request: QuickReply

### ISSUE THREAD

**Issue by JasonWSnoW** [peterhajas/MobileNotifier#135]
Okay so here is what I  was thinking: 
- Text message is received 
- user sees status-bar notification, clicks
- "Later" and "Reply" buttons appear 
- after hitting reply the message bar drops down (think qTweeter) revealing the message 
- user then has keyboard and text input as well as full view of the message (from the top to bottom it can just go lower to compensate for the length of the message, if the message is really long, the bar comes all the way down to cover the full-screen and the user can just scroll through the message
- Send is clicked, the notification system then recedes into the top and goes away

This would be very sick with a black, mostly opaque background (in my opinion) just because it would look like an actual skin that comes over whatever it is you're working on. 

One of the main things I think users don't want to see int he next quick-reply/overall notification system is the damn popup. Man, I'm getting effin tired of seeing an actual popup that's blue and in my way. This is more seamless. 

Just an idea, you're the director! 

ps - landscape mode would probably require something that goes from the left or right side of the screen.

**Comment by timnovinger** [comment]
This feature was added in later builds.
