### ISSUE TITLE
Please Bring back the black background

### ISSUE THREAD

**Issue by daverage** [peterhajas/MobileNotifier#136]
If you are using a different activator action to the double tap on home (I am using Multifl0w) you need to have some kind of dark background behind the notification window.  Otherwise you can not see the clear all button properly.

It used to do this.

Thanks!

**Comment by pocketlim** [comment]
Peter mentioned this has been fixed.

**Comment by daverage** [comment]
Ah cool, will look forward to beta 5 then!

**Comment by timnovinger** [comment]
Yes, this has been fixed. Thanks for your report!
