### ISSUE TITLE
Hidden Message.... It really needs to be added

### ISSUE THREAD

**Issue by ghost** [peterhajas/MobileNotifier#142]
Hey,

I LOVE the app. But I cannot use it.... I don't want the text from my messages to display at the top of my phone for anyone that is looking at my phone to see. I would like to see it hidden...
It is something apple has been doing forever, and it would make this app amazing.

But till then, I cannot really use it... I don't like that.

**Comment by EntouchGraphics** [comment]
Hello, Just thought I would pipe in and help out... Peter has previously stated that he will be added a settings app allowing some customization to the notifications. Please remember that this is still a beta version of the application.
