### ISSUE TITLE
Clear Notifications Button Disappears 

### ISSUE THREAD

**Issue by avaluxdev** [peterhajas/MobileNotifier#143]
Today, when I went to clear my notifications window by double clicking on the home button and then clicking "Clear Notifications", I noticed that the notifications box was up higher than normal and the "Clear Notifications" text/button was missing. A screenshot is located here: http://yfrog.com/gyy1qjsj .

Using Beta4; have yet to find a resolution to this issue.

**Comment by davidmichaelmalloy** [comment]
I have the same issue and posted a new Issue. I didn't see this one until after I posted, unfortunately.

https://github.com/peterhajas/MobileNotifier/issues/148

**Comment by avaluxdev** [comment]
Since the new beta4r1 release, I have not noticed this issue reoccurring. However, given the relatively short period between b4 and b4r1 (in which I saw this issue occur 3 times), that's not to say it won't occur with this latest update. I just thought I'd provide an update.
