### ISSUE TITLE
Inconsistent behavior of lockscreen notifications list

### ISSUE THREAD

**Issue by Einarin** [peterhajas/MobileNotifier#144]
Tapping the lockscreen notifications widget opens a list of notifications. These allow swipe to delete, but removing one does not remove it from the list on the multitasking switcher. It does seem to remove the lockscreen widget.

Steps to reproduce:
One active notification
Open list at lockscreen
Swipe to delete notification

Results:
Lock screen widget remains until unlock and relock.
Notification still listed in multitasking switcher.

**Comment by Einarin** [comment]
Recording another notification causes the old notification to be removed from the switcher. Perhaps the list isn't being updated?

**Comment by timnovinger** [comment]
I've marked this issue as invalid. This bug has already been fixed in the master branch, and should be pushed out soon. Thanks @Einarin!
