### ISSUE TITLE
Opening the multitasking switcher while a notification is present breaks switcher display 

### ISSUE THREAD

**Issue by Einarin** [peterhajas/MobileNotifier#145]
Opening the multitasking switcher while a statusbar notification is being displayed breaks the layout of the switcher.

Steps to reproduce:
Recieve notification while at home screen.
Open multitasking switcher without performing action on notification.

**Comment by peterhajas** [comment]
Thanks for this - I believe it has something to do with the doubleheight statusbar. I'll look into it.
