### ISSUE TITLE
"Clear pending" button difficult to read (transparency)

### ISSUE THREAD

**Issue by davidmichaelmalloy** [peterhajas/MobileNotifier#147]
When opening the Notification Board anywhere other than the home screen, the "Clear pending" button is very difficult to read as the background is transparent. This is most notable in an app like Facebook as the "Clear pending" button appears over the top of app and is almost completely impossible to read. Perhaps putting an oblong and opaque button behind the text would help.

Here is an example of how it looks when Facebook is open and I open the Notification Board: http://imgur.com/7h7iR

**Comment by peterhajas** [comment]
Fixed, will be rolled out shortly!

**Comment by davidmichaelmalloy** [comment]
Impressive fix! Looks fantastic!!
