### ISSUE TITLE
Notification Board Issue

### ISSUE THREAD

**Issue by davidmichaelmalloy** [peterhajas/MobileNotifier#148]
When switching between the notification board and an app, upon returning to the notification board I see this: http://imgur.com/mAVm1.

The "Clear pending" button is gone, and the first notification in the list is pushed up above the screen and out of view.

**Comment by avaluxdev** [comment]
FYI: Your image link isn't working.

**Comment by davidmichaelmalloy** [comment]
The period got pulled into the hyperlink: http://imgur.com/mAVm1

**Comment by peterhajas** [comment]
Duplicate of this issue: https://github.com/peterhajas/MobileNotifier/issues/143

Closing, please redirect further discussion there, thanks guys!
