### ISSUE TITLE
Lack of opacity behind dash

### ISSUE THREAD

**Issue by nandreetta** [peterhajas/MobileNotifier#149]
There is no opacity whatsoever behind my dash when I bring it up with a double click of the home button. This results in some ugly conflicts with whatever I have open behind it, as seen here: http://cl.ly/172I1Q220L38120P3k2y

**Comment by EntouchGraphics** [comment]
This is an issue that has already been fixed by peter hajas. Expect it in the next release of Mobile Notifier.

You can see the Issue Ticket here: https://github.com/peterhajas/MobileNotifier/issues/136

**Comment by peterhajas** [comment]
This has been fixed, as EntouchGraphics mentioned.

**Comment by nandreetta** [comment]
Thanks for addressing this and getting back to me. Sorry I was an idiot and failed to check the Closed Issues section in the first place. Looking forward to the release.

**Comment by peterhajas** [comment]
Not a problem! You reported an issue, which is great! I appreciate it nonetheless :)

Have a great day!
