### ISSUE TITLE
Lock screen view, double notification sound, and more…

### ISSUE THREAD

**Issue by melaus** [peterhajas/MobileNotifier#154]
(Posted as a comment. I guess it would be good to have it posted here as well.)

Thanks! This has been a great tweak that takes the iPhone to the next level! Some great work out there and it works quite well.

But, it might be worth looking into that if a notification arrives when the phone is in the lock screen, it doesn't show up on the menu bar area. So, you might miss it when you unlock the screen. Also, when you unlocked the screen and go read / reply a message for example, it would not clear that notification.

The notification page shown when launching the multi-tasking bar some times does not show as expected. The "clear pending" becomes white some of the time, making it difficult to read. Maybe a black semi-transparent background would work?

There's not a way to see all notifications on the menu bar when a new notification arrives after the previous one.

And, one irritating point is that when a new WhatsApp message arrives, for example, it plays both my default WhatsApp message sound and the Tri-tone system default sound. I'm not sure whether it's a problem of the notification system or what, but it would be good if this problem could be fixed.

I enjoyed your notification messaging software so much, and I wish to see more from it soon!

AL

**Comment by btaroli** [comment]
I don't recall that the lockscreen timeout -- if you don't swipe to unlock -- is affected by the presence of things to interact with. This is also true of other lockscreen modifications, like Notifier+. Unsure what the usefulness of a pop-up would be, considering this.

The "clear pending" issue was previously reported -- it is/was a transparency (of the background) issue.

If you want to see previous notifications, simply double-tap home button to bring up task-switcher, which also serves as home for MN's "dashboard".

The double notification sound issue has also previously been reported, and according to the YouTube interview posted today, sounds like there may be some fixes for (if not for all cases) in the upcoming b4r1 release :) can't wait!

Might be worth a quick review of other pending issues to see what else has been reported. :)
