### ISSUE TITLE
Needs Background to Dim

### ISSUE THREAD

**Issue by PrimaFacie** [peterhajas/MobileNotifier#156]
The background no longer dims when MobileNotifier's dashboard is open in apps.  If the app's background is white, the result is unsightly and, in many cases, almost unusable.

**Comment by PrimaFacie** [comment]
Ooops, looks like this has already been addressed.  I just found it mentioned several times on the "Closed Issues" page.

**Comment by peterhajas** [comment]
Thanks for closing this!
