### ISSUE TITLE
Lockscreen missed alert. 

### ISSUE THREAD

**Issue by mjeromes** [peterhajas/MobileNotifier#157]
After getting a text message the missed alert would not go away from the lockscreen even after I viewed the message.

**Comment by seancca** [comment]
You might have to remove it and reinstall but now the lock screen thing pops up even though I have it turned off. What is going on there.

**Comment by mjeromes** [comment]
After I view the message it still says that I have a missed alert on the lockscreen. "Not after I turn it off," is not in my post.

**Comment by seancca** [comment]
I was just saying as well to piggy back on that it still displays the lockscreen alert even though I have it turned off in settings. You might have to remove Mobilenotifier and then reinstall it so it works sorta right.

**Comment by mjeromes** [comment]
Oh ok thanks
