### ISSUE TITLE
LockInfo Incompatibility

### ISSUE THREAD

**Issue by ifonefox** [peterhajas/MobileNotifier#16]
When the MobileNotifier lockscreen notification counter is showing and Lockinfo is enabled, the notification counter is on top of Lockinfo. Picture: http://twitpic.com/44k04e

**Comment by jcrugzz** [comment]
I have the same issue.  Could you possibly make an option in settings to disable the notification counter? That would be excellent.  I like the new design btw.

**Comment by pedrovanzella** [comment]
Maybe a lockinfo plugin could be provided, or by some other way, have the notifications show up properly with lockinfo.

**Comment by NestorDave** [comment]
I second that, it will be great if there's a way to disable notification counter in the lockscreen, or actually the better way will be to have a lockinfo plugin for mobilenotifier

**Comment by lewc** [comment]
Plugin for lockinfo would be great but realise that might be a lot of work!

**Comment by NestorDave** [comment]
Yup, so the best thing to do will be to have an option to disable notification in the lock screen I think

**Comment by targit86** [comment]
A plugin isn't necessary IMO, LockInfo does a pretty good job of handling notifications.

I agree with jcrugzz & NestorDave, just add an option to disable MN on the lockscreen.

**Comment by peterhajas** [comment]
Is everyone in agreement - if I make the lockscreen view have a toggle, that is an acceptable fix?

**Comment by lewc** [comment]
That would be great thanks for the excellent work on this brilliant app

**Comment by dfishburn** [comment]
Yes, make it a toggle.  See the post titled "Setting page suggestions" for a round up of other items to also toggle or set.

**Comment by sebastianrothe** [comment]
a toggle would be nice for the beginning

**Comment by simonchunk** [comment]
Thanks guys, this has been doing my head in! Toggle would be awesome!

**Comment by Jonyjack** [comment]
EXACTLY, a toggle would be AWESOME! ;)

**Comment by peterhajas** [comment]
This has been fixed and will be rolled out in the next release, thanks!
