### ISSUE TITLE
Cannot open messaging app from lockscreen

### ISSUE THREAD

**Issue by chuckado** [peterhajas/MobileNotifier#160]
I am running 4.3.2.  Cannot open messaging app from lock screen.  I do not know if it is because I have a passkey to unlock the phone but I can preview the message but there is no option to open the app from the lock screen so it is automatically opened when i unlock..  If this is not a bug then I would be happy to suggest it as a new feature.

**Comment by io41** [comment]
Yes, please add this, or at least give an option for this behavior. I believe it's not a "bug", but rather that Peter Hajas desired behavior, see https://github.com/peterhajas/MobileNotifier/issues/106
