### ISSUE TITLE
Doesn't really agree with safari?

### ISSUE THREAD

**Issue by MythicDonut** [peterhajas/MobileNotifier#162]
This is a great app but I just want two things to be fixed:
1. I'm a guy who multitasks alot and the mobilenotifer app is sort of 'getting in the way'. You should try it and see for yourself. Go into safari and double click your home button, you'll see it sort of looks too congested, maybe find a way to make it look more cleaner? Please defiantly fix this!
2. This is minor but oh well, I simply just want the option to switch between the colours silver and black for the notifications bar. I loved the silverly notifications bar from beta 3 but in beta 4 you just took it away :(

**Comment by timnovinger** [comment]
Not sure what you're referring to about the first issue. The second issue you listed has been addressed in later builds. Thanks for the input!
