### ISSUE TITLE
Automatic Removal Of Notifications

### ISSUE THREAD

**Issue by sircrazy** [peterhajas/MobileNotifier#165]
iPod Touch 4G
iOS 4.2.1
MobileNotifier Beta 4 from official repository

Upon opening an alert from the multitasking window, mobile notifier does not always remove all instances of similar notifications. On some occasions it does.
Upon entering the application, mobile notifier has never recognized the connection between the notification and the application I opened and the alert remains there. (as described in the ModMyI video, alerts should recognize this)

This has been tested using the Messages application and receiving text messages from various sources.

I hope this is enough information on the issue,
Sircrazy

**Comment by peterhajas** [comment]
Is this still the case with the newest beta?

**Comment by sircrazy** [comment]
Tested with the messages app in newest beta, the issue can not be reproduced. It's coming along great man.
