### ISSUE TITLE
"Clear Pending" text on multitasking window

### ISSUE THREAD

**Issue by sircrazy** [peterhajas/MobileNotifier#166]
iPod Touch 4G
iOS 4.2.1
MobileNotifier Beta 4 from official repository

The test "Clear Pending" is sometimes unable to be read on the multitasking window, especially when apps with a white background are in use. This was first noticed with the white background of the messaging app. While in the app, I activated the multitasking window. The "clear pending" text becomes almost unnoticeable.

One solution may be to simply add a larger shadow/outline around the text.

Sircrazy

**Comment by peterhajas** [comment]
This is a duplicate of an already reported issue, and has been fixed. Will be rolled out shortly!
