### ISSUE TITLE
Quick Reply - Google Voice Client SMS Support?

### ISSUE THREAD

**Issue by Dadditude** [peterhajas/MobileNotifier#167]
I doubt this is something that will be available in early builds, but do you think you will eventually have Quick Reply support for Google Voice apps that support SMS, like GV Connect and Talkatone?

**Comment by timnovinger** [comment]
It's doubtful as each application would have to have an internal API for us to use. The reason quick reply works for the iOS Messages app is because there _are_ internal API's for sending SMS's.
