### ISSUE TITLE
Can't tap in b4r1 lockscreen dash

### ISSUE THREAD

**Issue by btaroli** [peterhajas/MobileNotifier#169]
The new display seems to overlap the display area used by Notifier+ lock view icons, preventing me from tapping on those. 

Similarly, it seems that tapping and swiping on entries in the MN lockscreen dash does absolutely nothing. Is this correct? Seems unusual, and change isn't noted in rel notes...

**Comment by btaroli** [comment]
Ah, I have found that the overlay of the Notifier+ icons only occurs once I've tapped on the MN item and the display expands. So if I tap again to collapse then the Notifier+ icons work fine. Still unsure why tap/swipe doesn't work in the notification list on the lockscreen dash now though. Did that change on purpose?

**Comment by ttopac** [comment]
I'm having a similar issue with biteSMS installed. I cannot either tap any notification or swipe any to remove, I don't have Notifier+ installed though.

**Comment by kristianpennacchia** [comment]
The MN lockscreen is not meant to be interactive. See https://github.com/peterhajas/MobileNotifier/issues/45#issuecomment-826849

**Comment by peterhajas** [comment]
This was changed on purpose, actually. As @kristianpennacchia mentioned, the lockscreen is not meant to be (at least destructively) interactive. This fixes the crash-on-lockscreen-delete bug, and also keeps the software interacting with Apple's stuff as nice as possible.
