### ISSUE TITLE
Bug on Alarm clock

### ISSUE THREAD

**Issue by b0ywarrior** [peterhajas/MobileNotifier#17]
After install MobileNotifier, I couldn't found the app at all but I begin testing with the Alarm Clock !
The result is Alarm Ring Ring and I cannot turn the alarm tone OFF !

**Comment by dynamacdude** [comment]
had same problem.

i am using my iphone as my alarm clock. i waked up a hour ago, because my iphone ringed, but i cant stop its ringing or snooze it. :D i mean, its nice feature for those who cant get up fast. ;D

so i had to respring the iphone via SBSettings to get it stopped.

**Comment by b0ywarrior** [comment]
Yep :D the same resolution.
Respring to stop its RINGING !

**Comment by baberim** [comment]
Yea..having this issue fixed would make this perfect for me. Thank you so much for this!!!!

**Comment by peterhajas** [comment]
Fixed in beta3r4, update in the repo!

**Comment by b0ywarrior** [comment]
Thx i will reinstall & help u find out more.
