### ISSUE TITLE
Lockscreen setting ignored

### ISSUE THREAD

**Issue by daverage** [peterhajas/MobileNotifier#171]
Installed the version pushed out on the 14/05/11 

Background is back which is great, but even with lockscreen notification switched off in settings, I still get the notifier in the lockscreen.

**Comment by takh** [comment]
I have the same problem. Since i have lockinfo, i wanted to turn all lockscreen stuff from mobilenotifier...

**Comment by peterhajas** [comment]
This has been fixed in beta5, please update!

**Comment by daverage** [comment]
Yep, installed and works a treat :)

**Comment by takh** [comment]
Working for me too. Thanks.
