### ISSUE TITLE
Not compatible with Lockinfo and BiteSMS

### ISSUE THREAD

**Issue by Zetsuo** [peterhajas/MobileNotifier#174]
In BiteSMS, the notification bar of the lockscreen obstruct the QuickReply and the QuickCompose of biteSMS

In Lockinfo, the notification bar of the lockscreen stay on top, after enter in a application via the notification system of lockinfo

**Comment by blerglemon** [comment]
Same happens for me with lockinfo, albeit not every time

**Comment by ttopac** [comment]
The problem with biteSMS can be seen from the following pictures:

http://img215.imageshack.us/img215/4624/photo2l.png
http://img196.imageshack.us/img196/2888/photo1ho.png

**Comment by timnovinger** [comment]
Compatibility with these tweaks is not planned, especially now that MobileNotifier has it's own quick reply functionality.
