### ISSUE TITLE
Enhancement: Re-add tap-to-open in lockscreen dash

### ISSUE THREAD

**Issue by btaroli** [peterhajas/MobileNotifier#175]
I'm noticing that the lockscreen dash has become extremely un-useful, in b4r1, when one can't even tap it to open apps. What's the point of seeing something there if I have to unlock and double-click, and tap again to actually see it? The utility seems significantly diminished.

**Comment by carlo-laitano** [comment]
I see your point and it's very valid. I wish we could tap to open as well, but it's not like the lock view is completely useless. Sometimes I just want to see if the notification is important or not to decide whether I should do anything else.

**Comment by btaroli** [comment]
Well, I think the pendulum swung too far the other way. I totally get not /modifying/ the state of notifications from the dash, but not even being able to tap into an app is silly. I laugh each time, actually, because I'll see a notification from MN on the dash and then use an icon indicator from Notifier+ (which also appears on the lock screen) to tap into certain apps (IM and SMS mostly). And then I think "Well, that /used/ to be simpler." For now I still have Notifer+ as a crutch to get around most of this.

I'd turn the dash off entirely with the current function level, but apparently that's a bug too (reported elsewhere). Needs a little more baking, this particular function area. Doesn't detract from my love of MobileNotifier, but it is a bit annoying.

**Comment by timnovinger** [comment]
The lockscreen is not supposed to be a user interactive element. Having this ability introduces a lot of headaches. For example, for those that have a passcode set there is no way to get around the necessity of passcode input from the user DURING the opening of the application.

The lockscreen itself is meant to be just that.....a LOCKed screen for only displaying data, and that's all MN will use it for.

Sorry dudes.
