### ISSUE TITLE
Disable MobileNotifier on LockScreen

### ISSUE THREAD

**Issue by amitsbajaj** [peterhajas/MobileNotifier#176]
Hi Peter and Everyone, 

Brilliant app! Everything was perfect and I had MobileNotifier disabled on the lockscreen through its settings and with the update, I am now receiving notifications on the lockscreen even though it has been disabled - anyway to stop this?

Thanks, 
Amit

**Comment by simonchunk** [comment]
Yes, also having this issue with latest update, the lockscreen on\off switch is not working!

**Comment by parterburn** [comment]
Same issue; seems to be that the switch in the settings no longer does anything.

**Comment by vincer** [comment]
Yep, same here.

**Comment by kurick** [comment]
I've had the same issue since beta4.  Has there been any news on this?

**Comment by amitsbajaj** [comment]
It's a known issue - I've heard from Peter on this and understandaly there are a lot of features on here that Peter and his team would want to get around to so I'm sure this is on the cards for being fixed sometime in the near future. 

Still an amazing tweak tho - one of the best out there.. thanks peter and your whole team!

**Comment by timnovinger** [comment]
I'm unable to reproduce this issue, turning off the lockscreen alerts via settings is working fine on the latest build.
