### ISSUE TITLE
clock / alarm cant be snoozed or be stopped

### ISSUE THREAD

**Issue by dynamacdude** [peterhajas/MobileNotifier#18]
hey guys,
i am using my iphone as my alarm clock. i waked up a hour ago, because my iphone ringed, but i cant stop its ringing or snooze it. :D i mean, its nice feature for those who cant get up fast. ;D 

so i had to respring the iphone via SBSettings to get it stopped.

**Comment by dynamacdude** [comment]
close duplicate (case 17)

**Comment by peterhajas** [comment]
Fixed in beta3r4
