### ISSUE TITLE
Notifications launch information (Alarms,viber,skype,tango) and scrollable-stackable notifications.

### ISSUE THREAD

**Issue by maxipedrosa** [peterhajas/MobileNotifier#19]
Hi peter!

We`re going to make MobileNotifier the best notifications app =)

3 esenttial features:

1-Notifications dont hold the "launch info" and cant launch apps directly to the content of the notification, because this, alarms dont dismiss, and VOIP calls dont hang up.
Temporally you can add exceptions for this concrete notifications meanwhile this feature is developed.

2-Scrollable notifications (or popup whit full info), whit this you dont really need open the app to read the whole message, maybe you need read the msg but dont need to reply or wathever.

3-Stakable or multiples notifications windows.

Sorry for me english, THANKS!!!

**Comment by ahti** [comment]
to the first issue:
it somehow seems like theres not the right information passed in application:FinishedLaunchingWithOptions: when the app for an notification is launched.

**Comment by gabarab** [comment]
I would love to see that MobileNotifier works with Viber, Skype and other VoIP apps.
Right now I am using Viber and I still get those nasty pop-ups whenever I receive a text message from Viber.
