### ISSUE TITLE
Personal Input on MobileNotifier

### ISSUE THREAD

**Issue by jcrugzz** [peterhajas/MobileNotifier#2]
Just wanted to give you some input on what i think having used the beta version you installed on my phone last friday.

Some issues i ran into:
1. When one of the notification bars (after having recieved a text message) is on the screen, you are not able to answer your phone if someone is calling you.  For some reason the sliding of the answer will not finish and answer the call.
2. The GUI Menu is very inconsistent.  It changes after purely refreshing it and is not sorted in any fashion.
3. The sent and saved menus have a mix of the same texts (sometimes they even switch to either menu). None of the sent are any that I have sent.
4. The links of each individual message does not link back to the correct one, just links back to the last one open in your message app.
5. Receiving multiple text messages and having it take over the screen.
6. Menu defaulting to be displayed on the lock screen rather than be hidden(I have found myself not using the menu itself due to it not being helpful at the moment).

I am sure you know a lot of this already i just wanted to give some helpful input to help you make it better.  Once you have the new gui setup im sure the functionality will be much better.

**Comment by peterhajas** [comment]
Hey there! Let me respond one-by one to these issues.
1. I will investigate this issue; this is clearly a pretty terrible thing for usability.
2. The AlertDashboard is going through some pretty rapid revision at the moment. It's currently just a "can I make it work?" thing. It's going to be refactored entirely.
3. Yeah, this is my fault. I have pretty terrible names for the categories. Eventually, they'll be represented by images. "Sent" are notifications that have been "Sent away" by clicking the 'x'. This needs to be made far far more clear, and I'm working at that.
4. This is an issue that I am also aware of - currently MobileNotifier relies on bundleID for  opening the alert, which loses a lot of context. I know how to make this work for SMSes, and this will be represented appropriately internally.
5. This has been fixed - I now only allow one message to occupy the screen at once, and it is replaced by others. This needs to be animated, clearly, but it's much better than cascading alerts.
6. The lock menu is the AlertDashboard again, which is not very useful. I'm going to write a custom lockscreen viewer that's 1) optional and 2) far less intrusive, such that you don't have to deal with it every time you look at your phone's lockscreen.

Thanks for making me aware of these issues! Once I get them sorted out with beta3, "Copious Cheerios", I'll be sure to let you know!

Let me know if you have any other further comments. I will leave this issue open until I resolve the issues you have noticed.

**Comment by Gbouck** [comment]
I'm sure this is probably related to #1: 

When my phone has locked and it asks for my unlock passcode, now, if I put in the wrong passcode, it doesn't say "Wrong Password - Try Again". It simply doesn't do anything. All the numbers are still there. I can backspace and correct the last number and once it's correct, it let's me in.
