### ISSUE TITLE
No icon for german users

### ISSUE THREAD

**Issue by sNick86** [peterhajas/MobileNotifier#20]
Hi there,
the "Messages"-App doesn't shows the icon.. maybe that's why in german the name for this app really is "Nachrichten" - do you make any localisations? :)

**Comment by peterhajas** [comment]
Hmm, I believe this is related to the icon grabbing bug. What device and OS are you on?

**Comment by glemmestad** [comment]
Same here. Norwegian language settings.
iPhone 3GS, iOS 4.2.1.

**Comment by qlandman** [comment]
Same happens when Dutch language settings are used. 
Using iPhone 3GS, iOs 4.2.1.

**Comment by rxacevedo** [comment]
I'm having the same issues. Using English language settings. iPhone 3GS, iOS 4.2.1.

**Comment by sNick86** [comment]
I'm on iOS 4.2.1 with my iPhone 3Gs.

**Comment by qlandman** [comment]
This issue has not been resolved for me after the latest update of MobileNotifier. I still do not see an icon when using Dutch language settings.

**Comment by Jayke** [comment]
Same for me in UK English on 3GS.
