### ISSUE TITLE
SMS sound fix suggestion

### ISSUE THREAD

**Issue by aznair** [peterhajas/MobileNotifier#207]
A lot of people seem to be complaining that MN plays the default Tri-Tone sound for SMS messages regardless of what the user actually set for the alert tone.

I've found that using [SBSMSAlertItem shouldPlayMessageReceived] and [SBSMSAlertitem playMessageReceived] to handle SMS alert tones will fix this issue.

**Comment by iMuggle** [comment]
I'm assuming you need to edit this into a file? Which file exactly are you changing?

**Comment by aznair** [comment]
In Tweak.xm, in the function "activateAlertItem", inside the block for SMS alerts, add:
if ([%c(SBSMSAlertItem) shouldPlayMessageReceived])
{
    [%c(SBSMSAlertItem) playMessageReceived];
}
Then in MNWhistleBlowerController.m, inside "alertArrivedWithData", remove the if block.

This isn't really the "right" place to put the sound handling code but for me it's the easiest way to make it work.

**Comment by iMuggle** [comment]
Thanks! That works!

**Comment by Drudoo** [comment]
To do it properly you need to find the AudioServicesPlaySystemSound variable that is the chosen sms sound. Looking over apples audiobox frame work, i cant seem to find it =/

**Comment by aznair** [comment]
Yeah that was my first choice as well but as far as I can tell no such identifier exists, only specific tones :(

**Comment by Drudoo** [comment]
Check out some info regarding the SMS sounds here: https://github.com/peterhajas/MobileNotifier/pull/266 quite interesting.

**Comment by timnovinger** [comment]
This issue was fixed in [this commit](https://github.com/peterhajas/MobileNotifier/commit/9bde7db0e336aa7d5d83a1232eda6d9b49aef7b8). Thanks for the bug report!
