### ISSUE TITLE
[Conflict] Lockscreen view incompatible with TV Tube Sleep

### ISSUE THREAD

**Issue by AKValle26** [peterhajas/MobileNotifier#215]
TV Tube Sleep is a jailbreak tweak which creates a screen-off animation when the sleep button is pressed (or screen timeout).

Expected: At lock screen, sleep button is pressed and screen-off animation occurs smoothly

Actual: At lock screen, sleep button is pressed but lockscreen "view" stays as static overlay during duration of animation, then disappears

**Comment by timnovinger** [comment]
Sorry, compatibility with this tweak is not planned.
