### ISSUE TITLE
Swipe to unlock should send alerts away

### ISSUE THREAD

**Issue by arsenm** [peterhajas/MobileNotifier#217]
If the alerts are displayed on the dashboard when the screen is locked, the alert dashboard covers up the keypad. It should go away if you try to unlock the phone.

**Comment by timnovinger** [comment]
This bug has already been fixed. Please update.

**Comment by arsenm** [comment]
It's still happening with beta4
iPhone 3g, iOS 4.2.1

http://files.whatmannerofburgeristhis.com/MNLockscreenBug.mp4

**Comment by timnovinger** [comment]
@arsenm it looks like you have your Activator setup incorrectly. You should change it to disallow opening MobileNotifier from a status bar swipe down on the homescreen only.
