### ISSUE TITLE
Passcode lock Issue

### ISSUE THREAD

**Issue by Mouxy** [peterhajas/MobileNotifier#22]
Hi
With mobilenotifier when you introduce a wrong passcode on lockscreen, it doesn't show the "wrong password" text and obviously the "wipe" option after 10 failed attemps doesn't work. 

Great job!

**Comment by Mihir14** [comment]
Yes, I have also encountered this issue. I feel it is a MAJOR problem, as this most likely disables the wipe system in 10 failed inputs. I have checked this problem by uninstalling MobileNotifier, and the invalid password prompt is reenabled. Please make this issue a PRIORITY as it is a major issue.

**Comment by ghost** [comment]
Same problem here!
I'm using an iPod Touch 4G, iOS 4.2.1

**Comment by salaman** [comment]
I'm having the same problem, and I would really appreciate a fix.
iOS 4.1 on iPhone 4

**Comment by peterhajas** [comment]
Thanks for posting this!

I've resolved the issue, and it'll be out in the next release!

Here's the commit: https://github.com/peterhajas/MobileNotifier/commit/2434fe3f7af0087faa751d596d36092fc56e8b6d
