### ISSUE TITLE
[BUG?] Lockscreen notification bar still clickable on password screen

### ISSUE THREAD

**Issue by kristianpennacchia** [peterhajas/MobileNotifier#222]
If you slide to unlock and the password screen comes up, you can still see and press on the lockscreen notification bar. I think it would be more natural if that notification bar was hidden/disabled for as long as the password screen is up.

**Comment by timnovinger** [comment]
This issue was fixed in [this commit](https://github.com/peterhajas/MobileNotifier/commit/0eaffc503adf2190085951b3ed19fe2e91328e02)
