### ISSUE TITLE
Statusbar Notification Back to Black 

### ISSUE THREAD

**Issue by mamoc** [peterhajas/MobileNotifier#223]
Is it possible to Switch it back to black?
Or to Switch it in the settings...!?

**Comment by itosan** [comment]
+1

Loved the status bar notification in beta 4!

**Comment by joneb** [comment]
+1

Black is the new ...ehh... black!

**Comment by kristianpennacchia** [comment]
Personally I like it better white. Maybe have an option to choose between them?

**Comment by TaylorMonkey-duplicate** [comment]
Option would be great.  Would even love the old striped background from Beta 3-- or even to switch to Beta 3's larger notification with the nice drop shadow.

**Comment by timnovinger** [comment]
A setting for this has been added in [this commit](https://github.com/peterhajas/MobileNotifier/commit/a6189573078975d21b9d3b3e5d7713f8755bb84a). Please be patient, it will eventually roll out to users.
