### ISSUE TITLE
[Improvements] Colour, Preview, and more...

### ISSUE THREAD

**Issue by neelo** [peterhajas/MobileNotifier#225]
first off, very good release, i now use this instead of bitesms.
but a few things could be improved.

1)  if you are planning to keep the message notification to show just the name, maybe make it a single bar notification, that way there will be no green status bar and will probably be easier to make landscape compatible.

2) when a message is closed or replied to via quick reply the badge on the messages app needs to go also, unless the later button is clicked.

3) bring an option to  change the colour of the notification, i personally liked black, maybe a variety of colours would give people that customization they want.

4) i noticed when i received a text that some of the words had wiggly red lines under them indicating words hadn't been spelt correctly. Stop it from spell checking texts you have received.

Everything else is fine! the new dashboard is perfect, it is something i actually suggested to do, i wrote it in a comment on your blog, and the lockscreen i have always liked, so no arguments there.
Just keep up the good work and please try and apply the improvements i suggested.

**Comment by BDudely** [comment]
+1 for the black status bar

**Comment by peterhajas** [comment]
Please split these up into separate issues.

**Comment by ghost** [comment]
+1 for number 2

**Comment by timnovinger** [comment]
Basic notification style switching has been added. I cannot replicate the issue with the spell checking.
