### ISSUE TITLE
Even with beta5 I'm still getting duplicate sounds

### ISSUE THREAD

**Issue by scalamanderr** [peterhajas/MobileNotifier#226]
I still get the default tri-tone then my sms tone (horn).

I thought this was fixed?

**Comment by iPWNF0RY0U** [comment]
its probs just a glitch with your phone. im not gettign that bug anymore. try to uninstall mobilenotifier and reinstall it.

**Comment by scalamanderr** [comment]
I did reinstall it. I'm using the stock messaging app, is there anything else it could be?

**Comment by iPWNF0RY0U** [comment]
just set the text tone in the settings to none. i don't know whats causing this. most people dont have it.

**Comment by scalamanderr** [comment]
Okay, tried that. Only the tri-tone plays when I receive a message through MN, when locked I don't get a sound or a vibrate. It's only when MN notifies me is when I get the duplicate sound.

**Comment by scalamanderr** [comment]
Okay, I uninstalled and reinstalled again, and now I get the proper sms tone at the lock screen, and only a tri-tone with MN, no duplicate, no horn, just the tri-tone.

**Comment by iPWNF0RY0U** [comment]
yes that should be normal. they havent implimented the changing on tones in mobile notifier yet.

**Comment by scalamanderr** [comment]
ohhh okay, so even when you receive a sms it plays the tri-tone regardless of your specified sms tone?

**Comment by iPWNF0RY0U** [comment]
yes.

**Comment by scalamanderr** [comment]
okay, thanks.

## 

Zed Chance
Sent with Sparrow

**Comment by TaylorMonkey-duplicate** [comment]
I'm also still getting duplicate sounds (for SMS messages at least).  Both the tri-tone and the tone selected for SMS messages in settings will play.  MobileNotifier should simply not play any sound and let the actual push notifications handle sounds themselves.  The the notification doesn't have a sound, MobileNotifier probably shouldn't add one either.  

This is a long standing bug with basic functionality that unfortunately makes MobileNotifier somewhat unusable for me without workarounds (like turning off SMS tones in settings and losing custom tones or deleting the actual sound file) that I hope will be fixed soon.

**Comment by btaroli** [comment]
The behavior I'm noticing on my iPhone 4 is a bit odd. When /outisde/ the Messages app, I get only the MN default sound. When I have Messages /open/ I sometimes get the settings defined sound, but even then sometimes I only hear MN. :-\

**Comment by timnovinger** [comment]
This issue was fixed in [this commit](https://github.com/peterhajas/MobileNotifier/commit/9bde7db0e336aa7d5d83a1232eda6d9b49aef7b8). Thanks for the bug report!
