### ISSUE TITLE
Unable to change alert sounds

### ISSUE THREAD

**Issue by univtex34** [peterhajas/MobileNotifier#23]
I work in an office of iPhones, so all of my alert sounds are changed from default. However, MobileNotifier only plays tritone. Am I missing something?

**Comment by rgomezc** [comment]
Apart from the fact that there is no other sound except de default Tritone, it appears that the settings for each kind of notification are not respected. For instance: I have Twitter and Facebook set to only show the message, not to do any sound, but with MobileNotifier it always sounds.

**Comment by omagus** [comment]
I know the app is in beta so im just going to agree with you, Yes i have found that tritone is playing as my text message tone surly the add on should not interfere with what text tone you have? At the moment im using Chime as my tone as tritone is assigned to voice mail tone and eBays outbid lol hope there is a fix for this next so we can use out own tones. Keep up the good work tho!

**Comment by btaroli** [comment]
I'd say this one is resolved now. :)
