### ISSUE TITLE
[UI] Text Correction Label Position

### ISSUE THREAD

**Issue by exiva** [peterhajas/MobileNotifier#230]
The label for text correction in the quick reply shows up underneath the word, and gets cut off. Could this be moved to the top of the text so it doesn't get cut off?

**Comment by timnovinger** [comment]
Fixed in [this commit](https://github.com/peterhajas/MobileNotifier/commit/b541c7eb23282cff9babcbbf36225985084b40ca). Thanks for the bug report!
