### ISSUE TITLE
[Bug] Locking Device with Alert expanded

### ISSUE THREAD

**Issue by exiva** [peterhajas/MobileNotifier#231]
In beta5 if you lock the device with the alert expanded, when you unlock it no more alerts show up. You also can't use the recall activator function to display alerts. Only remedy is to respring/reboot the device.

**Comment by iPWNF0RY0U** [comment]
thats why it suddenly stopped. good find.

**Comment by kristianpennacchia** [comment]
Nice find, I was wondering why this happened to me.

**Comment by timnovinger** [comment]
I am unable to reproduce this issue. Please re-open this if it happens again to either of you guys. Thanks!

**Comment by exiva** [comment]
Re-Opening this issue. Screencast attached of the issue. Happens all the time on 0.5.0 Using iOS 4.2.1 on a iPhone 3g.

http://www.screenr.com/bOss  Screencast of the issue.
