### ISSUE TITLE
MobileNotifier v5 not working at all on device

### ISSUE THREAD

**Issue by anthonyhart** [peterhajas/MobileNotifier#238]
To clear things up, I am running the latest firmware version on my iPhone 4.  Nothing happened after installing it the first time, however the MobileNotifier option was there in my settings.  Uninstalled, deleted the directory after logging in via SSH located in var/mobile/library.  Reinstalled and still nothing.  I heard there are compatibility issues with BiteSMS which I am running, but the notifications did not work with any app in general so I'm assuming that is not the issue.

**Comment by peterhajas** [comment]
What do you have installed? Please uninstall biteSMS and any other notification systems you may be using.
