### ISSUE TITLE
Click to open app from message in lockscreen.

### ISSUE THREAD

**Issue by Teemu-zz** [peterhajas/MobileNotifier#247]
Like you get a message on BeejiveIM, you see the message but can't open the app on lockscreen (you have to go to home screen and open the app). This is what on lockinfo can do and really want to do same way in MobileNotifier.

-Teemu

**Comment by Drudoo** [comment]
This is fixed now and will be uploaded as a pull request within hours. A moderator then has to merge the projects.

**Comment by kristianpennacchia** [comment]
Wont happen, see https://github.com/peterhajas/MobileNotifier/issues/45#issuecomment-826849
