### ISSUE TITLE
Is mobile notifier handle email notification?

### ISSUE THREAD

**Issue by reycosare** [peterhajas/MobileNotifier#248]
is this tweak handle email notification?. 
because i install this tweak then i receive email and it doesn`t appear like an mobile notifier bar?.

**Comment by ghost** [comment]
No it doesn't. But that would be a cool feature to add! Hint Hint Peter Hajas

**Comment by Drudoo** [comment]
You can get it to handle them if you install Mail Enhancer

**Comment by ghost** [comment]
Really? So if I install that it would work with the new MobileNotifier?

**Comment by Drudoo** [comment]
Yeah. You will get your notifications like facebook and twitter and you can open mail with it =) (you cant reply like sms)

**Comment by ghost** [comment]
I thought facebook and twitter notifications already came. YOU CAN EVEN REPLY? AWESOME!

**Comment by ghost** [comment]
How much is Mail Enhancer?

**Comment by Drudoo** [comment]
You CANT reply. And yes facebook and twitter is already there, it was just an example of how mail enhancer works

**Comment by Drudoo** [comment]
Mail enhancer is 1.99$ on Cydia

**Comment by ghost** [comment]
oh so u cant reply emails....:(

**Comment by ghost** [comment]
We should implment that feature

**Comment by Drudoo** [comment]
Yes 'we' should. But it is not that easy.

**Comment by ghost** [comment]
But if you click the email notification it brings you to your email app right?

**Comment by Drudoo** [comment]
Yes

**Comment by reycosare** [comment]
does mobile notifier handle facebook and twitter?
it seems i dont handle facebook

**Comment by Drudoo** [comment]
It does handle facebook. Again you CANT reply, but it will open facebook when you press it.

**Comment by reycosare** [comment]
but how can i test this.i tried so many message on facebook but i seems its not notifying me

**Comment by Drudoo** [comment]
You can try and uninstall MobileNotifier and see if you get normal facebook notifications. If you do, then you will get them though mobilenofitier too. 
Check your Notification settings in the Settings app to see if facebook is enabled.

**Comment by reycosare** [comment]
what are another third party app that mobile notifier handle?thank you

**Comment by Drudoo** [comment]
MobileNotifier handles every notification you get, which would normally pop up on your screen.

**Comment by reycosare** [comment]
so it handle tweetbot?

**Comment by Drudoo** [comment]
No. Tweetbot does not support notifications. It is not MobileNotifiers fault, it is Tweetbots limitation.

**Comment by reycosare** [comment]
ok2.thank you.need to install agoin native twitter app

**Comment by Davechode** [comment]
I'm not getting any email notifications whatsoever with this: I just did a clean install of the app, do I need to do any modifications to make it display email notifications?

**Comment by kristianpennacchia** [comment]
Mail.app doesn't give popup notifications, so MN can't handle it. But as Drudoo said, you can install Mail Enhancer from Cydia and then MN will work with Mail.app

**Comment by ghost** [comment]
Yes u have to go in the settings.

---Yuval

On Jun 4, 2011, at 1:00 AM, Davechode
reply@reply.github.com
wrote:

**Comment by exiva** [comment]
Mail.app doesn't popup a push alert dialog for mail. Thus MN will NOT display notifications.

However, download Boxcar from the App Store (It's a free app) add your email account and follow the directions to get those working, then setup twitter. You'll get push notifications for both twitter and email through MN (But can't reply to them.) clicking the notification will open up whatever twitter client you choose (Tweetbot, official twitter, etc.)
