### ISSUE TITLE
[IDEA] for your next release!

### ISSUE THREAD

**Issue by neelo** [peterhajas/MobileNotifier#249]
there should be 3 options as shown below instead of one button.

(1st image is original, 2nd is my photoshoped edit)
http://i728.photobucket.com/albums/ww281/neelo_prodz/1.jpg

Reply - hit reply and it will open a quick reply box

Open - hit open and it will take you into the messages app to reply

Delete - hit delete and it will mark as read and clear off notifications

---

(1st picture is original, 2nd and 3rd is my photoshoped edit)
http://i728.photobucket.com/albums/ww281/neelo_prodz/2.jpg

Reply - hit reply and it will open a quick reply box

Open - hit open and it will take you into the messages app to reply

Delete - hit delete and it will mark as read and clear off notifications

Quick reply on the lockscreen would benefit alot of people, mainly because it would save time, not having to unlock then reply.

---

Also when you have multiple notifications, maybe making the notification bar swipe-able
so you can swipe seamlessly between notifications (see below)

(1st image is original, 2nd is my photoshoped edit)
http://i728.photobucket.com/albums/ww281/neelo_prodz/3.jpg

**Comment by ghost** [comment]
I really love the 3rd idea!!!! Could really make MobileNotifier a bit easier. The other ideas are OK, but the 3rd one is AWESOME! Please add this feature.

**Comment by mamoc** [comment]
3rd one was something, i postet one or two weeks ago! i want this so much!!

**Comment by BDudely** [comment]
+1 for MobileReply on LS

**Comment by Drudoo** [comment]
All the ideas are great and probably not that hard to incorporate (except the third one). I will try take a look at it whenever my computer lets me test my builds...
