### ISSUE TITLE
FEATURE REQUEST - Notifications should fade out after some time

### ISSUE THREAD

**Issue by tralafiti** [peterhajas/MobileNotifier#25]
like the titel says: i would love to see notifications fade away without after x seconds - maybe make the timespan editable via settings.app

**Comment by peterhajas** [comment]
Added!

https://github.com/peterhajas/MobileNotifier/commit/4cd813eb9c62d7a1c0641f22637899d6be5727ad

Thanks for the request! This will be rolled out in a future update of MobileNotifier.
