### ISSUE TITLE
MobileNotifier, LockInfo and BiteSMS

### ISSUE THREAD

**Issue by amitsbajaj** [peterhajas/MobileNotifier#250]
Not so much as an issue as just wanted to point you guys into the direction of an article I have written with full screenshots of how to seamlessly get MobileNotifier, LockInfo and BiteSMS working together. This is probably an amalgamation of many posts here.. 

There are still some issues like sounds and the such, but I am working on a work-around as much as I can. 

http://theforbiddenapples.wordpress.com/

Twitter me on @_amitsbajaj or @theforbiddenapp for more information if required

**Comment by Drudoo** [comment]
Going to take a look at this. Looks interesting =) I am using iRealSMS so probably wont work just as good, but lets see =)

**Comment by amitsbajaj** [comment]
you never know ;) please do let me know though if it works.. I'm interested to see if it works better/worse than BiteSMS with the MobileNotifier integration
