### ISSUE TITLE
Edit statusbar by myself?

### ISSUE THREAD

**Issue by mamoc** [peterhajas/MobileNotifier#252]
Is it possible to edit the new statusbar from beta5 back to beta4 statusbar by myself?
when I root my iPhone i can find /Library / Application Support / MobileNotifier with the .png but where to edit font color to white??!

**Comment by jada855** [comment]
Looking for a response to this answer as well seems like everyone is trying or wanting the status bar back to beta 4's style it was really nice and would unify the UI design. Hopefully someone will respond soon thanks.

**Comment by Drudoo** [comment]
Looking in the source code it is not hard to get it back. Without recompiling it, it is impossible.

**Comment by jada855** [comment]
Thanks for the reply I am a visual designer but tried to do a developers job last night. I was able to download mobile notifier to try and change the graphics but I was not successful with the installation of FINK. So I used SSH to find the "mobile notifier" directory on my phone there I was able to make a black png file to replace the updated white one. But ran into the problem of the incoming notification text color being black and not knowing where I could change it. The original status bar from beta 4 was awesome. If I could somehow combine with beta 5 it would be perfect! thanks for your help.

**Comment by Drudoo** [comment]
I am trying to code a new setting so you can chose which style you want. I am a bit rusty in the iOS language but lets see how it goes =)

**Comment by jada855** [comment]
Drudoo that would be awesome keep us posted thanks.

**Comment by mamoc** [comment]
oh yesss, i want the black statusbar back!!!

**Comment by Drudoo** [comment]
I added the code now, not 100% sure it will work, since I can't test it yet. My dpkg dependencies are still installing (takes forever) and then i need to compline and test it. I have uploaded the code to my fork so Peter (and others) can check it out.

**Comment by mamoc** [comment]
Brilliant Drudoo!! Can I anything do or test it without being developer or programmer...?! So exited.... ;-))

**Comment by jada855** [comment]
Drudoo,

Thanks for doing this hope to be able to install it soon! How would we go about downloading it or would it be a official release?

**Comment by Drudoo** [comment]
Relax =) I have never compiled for a jailbroken devise before, so it might take some time before I can test it. When it is tested Peter needs to incorporate it in the official code (if he wants it there) and then it can be released. It is not something that happen over night. Sadly enough =(

**Comment by mamoc** [comment]
Hopefully Peter Hajas is not too far away........ ;-)

**Comment by jada855** [comment]
:) Oh okay thanks for the update

**Comment by Drudoo** [comment]
I have compiled the code and added a new setting http://cl.ly/1N1m072C0T31342r472w it kind of works (since it changes the image) check it here http://cl.ly/0j3G2N2o0n462t0M1m0f but the font is not working right now and so is the revert back setting. I will have to look more in to it! More updates to come!

**Comment by mamoc** [comment]
settings looks nice!! if the font was white it would be perfect! :-)

**Comment by jada855** [comment]
Drudoo,

Thanks for the update and screens I ran into the same problem when switching the .png file. Have no clue where the type color line of code would be thanks again!

**Comment by Drudoo** [comment]
I found the line of code and will run a few test to see if i can figure it out correctly =)

**Comment by Drudoo** [comment]
My preferences are not working at all. But i got the bar looking good. http://cl.ly/3h0C1o1S1j0m2F1G2Y0e I will de-prioritize this problem, until i find a solution to how the preferences work.

**Comment by mamoc** [comment]
how did you got the font color white?
the png of the background is something i can edit by myself...

**Comment by jada855** [comment]
Drudoo,

So close! I guess by being a visual person this is something I really wanted. To make sure I follow correctly in order to make the text on the status alert white. I would need to recompile the entire application? I can find and update the .png files with out a problem.

**Comment by Drudoo** [comment]
It is in the code. If you can edit and compile the code then you just need to edit: 

```
alertBackgroundImageView.image = [UIImage imageWithContentsOfFile:@"/Library/Application Support/MobileNotifier/statusbar_alert_bg.png"];
alertHeaderLabel.textColor = [UIColor colorWithRed:0.000 green:0.000 blue:0.000 alpha:0.9];
alertHeaderLabel.shadowColor = [UIColor whiteColor];
```

to 

```
alertBackgroundImageView.image = [UIImage imageWithContentsOfFile:@"/Library/Application Support/MobileNotifier/alert_bg_small.png"];
alertHeaderLabel.textColor = [UIColor colorWithRed:1.000 green:1.000 blue:1.000 alpha:1];
alertHeaderLabel.shadowColor = [UIColor grayColor];
```

**Comment by mamoc** [comment]
:-(
how do i compile it?!? where is the file i have to edit?
oh man, i'm graphic designer, not developer ;-) but i try to give my best!!

**Comment by jada855** [comment]
Drudoo,

Thanks for the tip- but compiling code is where I fall short :( is the section of code some where I can reach via SSH in a plist or other editable text file?

**Comment by Drudoo** [comment]
Recompiling the code is hard. You need to go though Peters guide in the ReadMe file.

There is no string of code you can ssh in to. Since it is all compiled together it is un-readable. 
I would like to upload 'beta' releases for testing but Peter is not responding when i write to him, so i cant get his permission.

**Comment by jada855** [comment]
Drudoo,

I feared that thanks for the help though much appreciated and thanks for reaching out to Peter!

**Comment by timnovinger** [comment]
I've made this a priority. Stay tuned.

**Comment by jada855** [comment]
Timnovinger,

Awesome definitely looking forward to the update. It's so funny the day of the beta 5 release I was thinking to myself man I wish the task switcher was transparent like the home screen and status bar. I checked cydia and there was the update! I was excited only to find out that the status bar was changed :) thanks again!

**Comment by timnovinger** [comment]
The ability to choose either dark or light alert styles has been added in [this commit](https://github.com/peterhajas/MobileNotifier/commit/a6189573078975d21b9d3b3e5d7713f8755bb84a).

**Comment by jada855** [comment]
timnovinger,

Thanks for adding this- I have to admit I am not a developer am I able to download and install the update?

**Comment by mamoc** [comment]
How do i install this Option on my iPhone??? :-/

**Comment by timnovinger** [comment]
To install this latest addition to MobileNotifier you have two options: Download, compile, and install the project yourself or wait for it to be pushed out via the Cydia repo.

**Comment by mamoc** [comment]
Ok thank you!!!!!!
One last question for this threat: Your modification will roll out in the Next ofiicial Version of mobilenotifier?
When will it Be released?

**Comment by jada855** [comment]
timnovinger,

Quick question from the link you posted earlier which link do I download? I see the download button at the right but there are different versions. I going to attempt to download and compile thanks.

**Comment by timnovinger** [comment]
Simply follow the instructions in the readme that outline how to pull
and build the project.

Sent from my iPad

On Jun 2, 2011, at 11:45, jada855
reply@reply.github.com
wrote:

**Comment by Drudoo** [comment]
Just tested this and it works great. The new settings panel is a lot better =)

**Comment by mamoc** [comment]
I WANT THIS SOOOO MUCH!!!
checking cydia like every 10 minutes....

Am 02.06.2011 um 18:46 schrieb Drudoo reply@reply.github.com:

**Comment by jada855** [comment]
Mamoc,

I feel the same way lol! I just got through messing around with fink and was able to create a .deb file to install on the phone. Not sure if it is going to work. But I sure do feel a whole lot smarter :)

**Comment by Drudoo** [comment]
I don't think this will be released just yet. The black bar needs a new X button to go with it.

**Comment by jada855** [comment]
Anyone know the path to find libactivator.dylib ?

**Comment by Drudoo** [comment]
/usr/lib/libactivator.dylib

Btw the whole project has been updated with a new X. So redownload or update your fork =)

**Comment by jada855** [comment]
Drudoo,

Thanks glad I asked I completely had the wrong file. Making my way down the instructions to install!

**Comment by Drudoo** [comment]
Np :) it was quite hard for me to find the first time too ;)

**Comment by jada855** [comment]
Drudoo,

I understand this is not the install help section but can you shed some light on the "Build" instructions? It says to run "Make" and then "Make Package" which directory do I run this on? I followed the instructions up to this point I am so close! thanks again!

**Comment by Drudoo** [comment]
You run it on the MobileNotifier directory you downloaded from github. Use cd to point to it.

**Comment by mamoc** [comment]
@peterhajas Please release it soon!!! it Is making us crazy.... ;-)))

Am 03.06.2011 um 00:16 schrieb Drudoo reply@reply.github.com:

> You run it on the MobileNotifier directory you downloaded from github. Use cd to point to it. 
> 
> Sent from a Random Apple Device
>

**Comment by jada855** [comment]
Drudoo,

Yeah I hear you I am the furthest thing from being developer minded!! breaking a sweat to get through the install instructions :( but I had to try! I swear my brain has expanded!  cant get the "Make" command to work can you post a example of how to do so. You might flip out if you see how I am trying to execute the command! thanks for everyone's help up to this point!

**Comment by jada855** [comment]
Here is what I am using in terminal

MacBook-Pro:~ Jae$ cd ~/code
MacBook-Pro:code Jae$ make
make: **\* No targets specified and no makefile found.  Stop.

**Comment by Drudoo** [comment]
You need to point inside the MobileNotifier folder. So it is something like ~/code/MobileNotifier
Inside your folder make sure that the first line in the Makefile is pointing to the right location og Theos on you computer.

**Comment by Drudoo** [comment]
Also remember to set the GO_EASY_ON_ME to 1

$ export GO_EASY_ON_ME=1

**Comment by mamoc** [comment]
I don't get it............... :-((

**Comment by Drudoo** [comment]
@mamoc please explain.

**Comment by mamoc** [comment]
it is too much for my little visual/graphic brain... I tried, but failed.
Is there any way to geht mobilenotifier Beta4 back to my phone without 1.000 terminal codes?

**Comment by mamoc** [comment]
ok, beta 4 running.

**Comment by jada855** [comment]
@Drudoo,

I am getting closer forgot to download the SDK :) but I understand now how the make file is working as I was able to open it up and change the paths for theos. Almost there!

**Comment by Drudoo** [comment]
When it is first up and running, then it is really easy. The setup is the hard part.

**Comment by jada855** [comment]
@ Drudoo,

Here is my terminal window I am getting a directory not writable when I run the make command. I also tried running "sudo make"

MacBook-Pro:MobileNotifier Jae$ export THEOS=/opt/theos/
MacBook-Pro:MobileNotifier Jae$ export SDKVERSION=4.3
MacBook-Pro:MobileNotifier Jae$ export GO_EASY_ON_ME=1
MacBook-Pro:MobileNotifier Jae$ make
/opt/theos/ is not writable. Please run /opt/theos//bin/bootstrap.sh substrate manually, with privileges
Any help would be appreciated!

**Comment by kristianpennacchia** [comment]
You need permissions for that directory. I just went in to that directory and gave full permissions to bootstrap.sh through getinfo. Not sure if thats the right thing to do, but it worked fine for me.

Using sudo make will ignore the environment variables (your exports), so I wouldn't bother with that.

**Comment by jada855** [comment]
Gentlemen,

who have helped me out on this thread I thought it was "victory" my eyes got "HUGE" my heart skipped a beat and the terminal window began to scroll! but I am now getting these errors. I did try to decipher just not able too.

Bootstrapping CydiaSubstrate...
 Compiling iPhoneOS CydiaSubstrate stub... default target?
 Compiling native CydiaSubstrate stub...
Making all for tweak MobileNotifier...
 Preprocessing Tweak.xm...
 Compiling Tweak.xm...
cc1objplus: warnings being treated as errors
Tweak.xm: In function ‘void -[PHACInterface setDoubleHighStatusBar:](PHACInterface*, objc_selector*, BOOL)’:
Tweak.xm:251: warning: no ‘+sharedDataManager’ method found
Tweak.xm:251: warning: (Messages without a matching method signature
Tweak.xm:251: warning: will be assumed to return ‘id’ and accept
Tweak.xm:251: warning: ‘...’ as arguments.)
Tweak.xm:258: warning: no ‘-toggleSimulatesInCallStatusBar’ method found
make[2]: **\* [obj/Tweak.xm.o] Error 1
make[1]: **\* [internal-library-all_] Error 2
make: **\* [MobileNotifier.all.tweak.variables] Error 2

**Comment by timnovinger** [comment]
This is a known issue. Run `export GO_EASY_ON_ME=1` from the terminal and then try running `make` again.

## 

## Tim Novinger

Twitter:  @timnovinger
Skype: tim.novinger
Mobile: 260.918.4937

## Web:  timnovinger.com

Sent with Sparrow (http://www.sparrowmailapp.com)

**Comment by jada855** [comment]
Update!

I am seriously all teary eyed! I have a .deb file!!!! I just closed the terminal window and retyped everything

**Comment by jada855** [comment]
Thanks to everyone who lend their time to help. I have it up and running and the status notification looks nice! thanks again!

**Comment by Drudoo** [comment]
@jada855 glad you got it working! =)
