### ISSUE TITLE
[IMPROVEMENT] keyboard

### ISSUE THREAD

**Issue by neelo** [peterhajas/MobileNotifier#255]
nothing major, just something cosmetic, shouldnt be too hard to do, instead of using the grey keyboard, make quickreply bring up the transparent black keyboard that bitesms and irealsms bring up in quickreply.
will make the design look much neater on the whole.

**Comment by Drudoo** [comment]
Added  
textBox.keyboardAppearance = UIKeyboardAppearanceAlert;  

to 

MNAlertViewController.m 

As said before. I cant test it yet. Will keep you updated when i can.

**Comment by neelo** [comment]
thanks, where do i find that?

**Comment by Drudoo** [comment]
You cant do that without recompiling the whole project and manually installing a new .deb file.

**Comment by neelo** [comment]
ohh :(
guess its up to Peter

**Comment by Drudoo** [comment]
I got good and bad news! I have compiled and tested the new keyboard and it works! Check it out here http://cl.ly/0j3G2N2o0n462t0M1m0f

**Comment by neelo** [comment]
Yes that looks much better

**Comment by timnovinger** [comment]
The keyboard style was updated in [this commit](https://github.com/peterhajas/MobileNotifier/commit/4902593af8d525b639edc164f2cda5f8aa4978db), and will be rolled out to users at some point.
