### ISSUE TITLE
MobileNotifier and Third Party Apps

### ISSUE THREAD

**Issue by Heavens-Cookie** [peterhajas/MobileNotifier#257]
Hi question there is any way to use the mobilereply for other apps that is not sms? because when i get a message from yahoo or ebuddy everything works great but im not able to reply from the lil window(send button dont come up) like you do when u get an SMS.

Thanks =)

**Comment by Drudoo** [comment]
It is defiantly possible, the real question is who is going to use the time and implement it =P I have done it myself with Twitter (in another app) and it is not extremely hard to do.

**Comment by reycosare** [comment]
Can you give a tutorial on how to do it?.cause it only works on sms for me.

**Comment by Drudoo** [comment]
It is not something you just do and it will take a lot of coding to do + you need to compile it after and manually install it.

**Comment by Heavens-Cookie** [comment]
that's great that can be done but first thing first what should i learn in order to try to make this happened cos i really wanna have it =)

**Comment by Drudoo** [comment]
Well to make this, you need to be able to code in cocoa and know Apple's API. Then you need to know Facebook Connect, Twitter and other companies' API. It is hard work and not something that is easily accomplished. You need to program one app's notification at a time.

**Comment by Heavens-Cookie** [comment]
=) okie dokie time to study then :P maybe at some point soon i can make it happened thanks!! =).
