### ISSUE TITLE
Better Lockscreen Feature Request

### ISSUE THREAD

**Issue by ghost** [peterhajas/MobileNotifier#259]
Maybe we can have a lockscreen where if you don't have a passcode you can click on a missed notification and it brings you to that app. And maybe you can have quick reply on the lockscreen by clicking the sms notification.

**Comment by Drudoo** [comment]
I am pretty sure there is already an open Issue of this.

**Comment by ghost** [comment]
wat is the link?

**Comment by Drudoo** [comment]
I dont know. Look for yourself =) There is a search function.
