### ISSUE TITLE
No retina settings icon (Icon@2x.png).

### ISSUE THREAD

**Issue by magn2o** [peterhajas/MobileNotifier#261]
There needs to be an appropriately sized, retina, settings icon (Icon@2x.png). Without it, the MobileNotifier entry looks "out of place" eg. the "MobileNotifier" text is offset to the right and the icon is way too big.

I placed resized Icon@2x.png (57x57) and everything is now fine.

**Comment by reycosare** [comment]
how to change?

**Comment by timnovinger** [comment]
This issue should be fixed by [this commit](https://github.com/peterhajas/MobileNotifier/commit/401d36da0c2b8db5d5b4b2d2a58b07d52df61099).
