### ISSUE TITLE
MN notification sound issue with LOCKinfo and Bitesms.

### ISSUE THREAD

**Issue by chengsz** [peterhajas/MobileNotifier#264]
Forbidden Apples has a really nice writeup of integrating lockinfo, bitesms, and MN, it is awesome. 
http://theforbiddenapples.wordpress.com/2011/05/30/mobilenotifier-bitesms-and-lockinfo-the-seamless-and-beautiful-relationship/

However, the issues arise that by doing so, getting a notification or text while on standby or in lockscreen, there will be no sound, this is due to settings change so that in unlock screen (or in app), there wont be double texttones.  Playing ard for a while, I think it is likely because MN has its own sound system? is there a way on ur end to disable it?

**Comment by Drudoo** [comment]
Since this is not a direct problem to MN (You are using BiteSMS as your client) it should not be posted here. 
Yes. MobileNotifier has its own soundsystem and it is not possible to disable at the moment.
