### ISSUE TITLE
Apps Crashing...

### ISSUE THREAD

**Issue by JacobVengeance** [peterhajas/MobileNotifier#27]
I left my iPod touch sitting over night and I got about 5 notifications all of which were to Google Voice application. I noticed them from the lockscreen and bubbles on springboard, problem is that I cannot open said app cause it just loads till a notification bubble comes up on bottom and crashes. I could not get a bug report from it, but I know MobileNotifier was the only thing I had installed since I just restored to 3.1.2. Anyone else get this?

**Comment by WG5516** [comment]
I'm definitely having similar issues. Oddly, mine started after I updated to the new version of Lockinfo. I sent my crash report to that developer and he told me that it wasn't their app causing the crash, but something called Mobile Notifier. Both tweaks were working working great w/ my Line 2 app (Voip) and Google Voice app. Not sure what happened between Tuesday & Thursday of this week to cause the problems to start.

**Comment by peterhajas** [comment]
What apps are crashing? I don't understand the bug report, can you elaborate?

**Comment by WG5516** [comment]
I can provide the crash report. The main app that's crashing for me is Line2. When I receive an SMS, it crashes MobileNotifier & it restarts the iPod 3G (4.2.1).

**Comment by WG5516** [comment]
Something happened between Tuesday & Thursday of last week. I remember downloading the app on Monday and everything was great. Worked well until I believe I updated MobileNotifier on Wednesday.

**Comment by peterhajas** [comment]
Ahh, I see. This may have something to do with another issue. If you could email me (peterhajas@gmail.com), I'd love to send you a prerelease build that may fix these issues?

**Comment by peterhajas** [comment]
Fixed this! It'll be rolled out in the next release!

https://github.com/peterhajas/MobileNotifier/commit/f31779a9a036a3d92f337fb1348cb44c28b5b682
