### ISSUE TITLE
SBSettings Compatibility

### ISSUE THREAD

**Issue by gamemasta0** [peterhajas/MobileNotifier#270]
I have only noticed this on the lockscreen, but MN overlays SBS even when the settings pane looks like it should come down above it, not sure if it is possible to fix, but it would be nice if I didn't have to worry about conflicts between the two.

**Comment by michiz** [comment]
It's the same on my iPhone 3G 4.2.1 ...
The z-factor should be changed if this is possible... if MN is over the SBS you are not able to touch on SBSetting's buttons..
