### ISSUE TITLE
Incompatibilty with SlideAway tweak

### ISSUE THREAD

**Issue by dedo93** [peterhajas/MobileNotifier#271]
With this tweak installed the lockscreen notifications doesn't disappear when unlock the phone

**Comment by Drudoo** [comment]
I will take a look at this.

**Comment by Drudoo** [comment]
It seems that SlideAway is not actually unlocking the phone but rather opening apps on top of the lockscreen. MobileNotifier is only dismissing when you unlock the phone.

**Comment by dedo93** [comment]
This is what's happen: http://img824.imageshack.us/img824/3452/imagehli.jpg

**Comment by BDudely** [comment]
@dedo93 I would try turning off lockscreen alerts in the MobileNotifier settings

**Comment by DHowett** [comment]
SlideME is doing something wrong here. Among the many other things it does
wrong.
On Jun 2, 2011 2:39 AM, "dedo93" <
reply@reply.github.com>
wrote:

**Comment by timnovinger** [comment]
Compatibility with SlideAway is not planned, sorry.
