### ISSUE TITLE
Goin into Safe Mode

### ISSUE THREAD

**Issue by carpstriker** [peterhajas/MobileNotifier#273]
Occasionally the phone will go into safe mode when a notification should appear. Is there any file I can send for you to debug or anyway I can help you work this out??

**Comment by BDudely** [comment]
This also happens to me, on iPhone 3GS iOS 4.3.3

**Comment by Drudoo** [comment]
What phone and OS version are you using?

**Comment by carpstriker** [comment]
iPhone 4, iOS 4.3.1

**Comment by Drudoo** [comment]
Hmm that is the weird. I am using the exact same and never had any problem. Can you post what other tweaks and apps from cydia you have installed?

**Comment by carpstriker** [comment]
ive gonethrough cydia, removing some tweaks that I don't use. But I've left in tetherize - this may be the cause, so wanted to see if it was.
