### ISSUE TITLE
SlideAway NOT COMPATIABLE

### ISSUE THREAD

**Issue by ghost** [peterhajas/MobileNotifier#277]
Can u make MobileNotifier compatiable with Slideaway with the lockscreen? If I have a notification it has the dropdown window on the lockscreen, but when I unlock the device it stays. Can u make it comapitable and release a minor update to Mobilenotifer soon.

**Comment by DHowett** [comment]
This is slideaway's fault. It is not unlocking the device properly.
On Jun 3, 2011 6:55 PM, "ymarcus" <
reply@reply.github.com>
wrote:

**Comment by timnovinger** [comment]
Sorry, compatibility with this tweak is not planned.

## 

## Tim Novinger

Twitter:  @timnovinger
Skype: tim.novinger
Mobile: 260.918.4937

## Web:  timnovinger.com

Sent with Sparrow (http://www.sparrowmailapp.com)
