### ISSUE TITLE
Double Notifications

### ISSUE THREAD

**Issue by ryangball** [peterhajas/MobileNotifier#28]
When the screen is off, I can receive a text message and the MobileNotifier notification pops up, the screen will turn off again like normal then when I hit the home button to turn the screen on again, the stock iOS notification pops up as well. So I have both notifications showing me the message.

Got the notification
http://ryangball.com/wp-content/uploads/2011/02/IMG_1530.png

Screen turns off then I hit the home button to turn the screen back on
http://ryangball.com/wp-content/uploads/2011/02/IMG_1531.png

**Comment by dschuchart** [comment]
I am having this same issue.

**Comment by ryangball** [comment]
I'm on a 32gb iPhone 4, 4.2.1 jailbroken with greenpois0n
