### ISSUE TITLE
[ISSUE] No functionallity at all?

### ISSUE THREAD

**Issue by j0n3zz** [peterhajas/MobileNotifier#280]
Hey there.

I just downgraded my iPod from iOS 4.3.3 to 4.3.1 since a lot of Jailbreak tweaks work better on 4.3.1.
Now suddenly, MobileNotifier is not functioning at all? (at least for eBuddy, Viber & Skype)

I tried everything, and nothing works :/

Help?

**Comment by kristianpennacchia** [comment]
Skype and Viber are on the ignored applications list, so if you browse to "Library/Application Support/MobileNotifier" on your iPod using iFile or something similar, you could remove them from the property list file.
But they were added there for a reason, so there might be problems.

**Comment by j0n3zz** [comment]
Thanks mate!

Den 05/06/2011 kl. 18.09 skrev kristianpennacchiareply@reply.github.com:
