### ISSUE TITLE
[Feature Request] Email notifications

### ISSUE THREAD

**Issue by LMD75** [peterhajas/MobileNotifier#288]
I am currently using Mail Enhancer to handle this as a workaround.  I would like to request that this be added into MN.

**Comment by timnovinger** [comment]
This is a duplicate issue of [#248](https://github.com/peterhajas/MobileNotifier/issues/248). Please see that ticket for reasons as to why this is not possible with MobileNotifier alone.

**Comment by LMD75** [comment]
Thank you for the response.  I was not logging it as a problem /issue but instead a feature request.   IOS 5 Beta and Lockinfo have this feature and I think it would be a another tick in the box for MobileNotifier if it too had this feature.  Do you have any plans on adding this in the near future?
