### ISSUE TITLE
Default Tri-Tone still being played

### ISSUE THREAD

**Issue by bmorgenthaler** [peterhajas/MobileNotifier#291]
I'm on VZW iOS 4.2.6 with the latest MobileNotifier and I still get the default Tri-Tone sound for SMS messages with or without BiteSMS installed and with the system SMS sound set to none or Telegrah. Though when I set it to Telegraph I get both sounds, the Tri-Tone then Telegraph.

**Comment by timnovinger** [comment]
This should be fixed in later builds, please be patient in waiting for it to hit Cydia.
