### ISSUE TITLE
Quick reply don,t exist.

### ISSUE THREAD

**Issue by Husnihalim** [peterhajas/MobileNotifier#293]
Everytime i open the notification, the quick reply box and send icon dont exist.. There is no way to quick reply. Only those two boxes on the bottom left corner. I am using iphone 4 4.3.2.. Somebody help me.. Tq

**Comment by kristianpennacchia** [comment]
Quick Reply is for SMS only. Not sure if theres plans to implement it for other apps too

**Comment by timnovinger** [comment]
Please verify that this is happening on a non-SMS notification.

**Comment by Husnihalim** [comment]
Im using bitesms. so sms notifications does not come from the mobilenotifier..i wish this one works with whatsapp or nimbuzz. It kinda a big hassle, having to go back to the apps to reply.

**Comment by timnovinger** [comment]
Sorry, SMS notifications are the only type that MobileNotifier handles for quick reply. It's far too difficult to tap into the API's of each application out there.

**Comment by Husnihalim** [comment]
thank you.
