### ISSUE TITLE
AlertDashboard doesn't show when double click home button

### ISSUE THREAD

**Issue by Santonio84** [peterhajas/MobileNotifier#294]
Hiya!

I just installed mobilenotifier but when double click the home button AlertDashboard doesn't show. I had lockinfo installed and I removed it, but AlertDashboard still doesn't show. 
¿What could be the problem?

Thnx a lot!!

**Comment by kristianpennacchia** [comment]
In the Settings.app find MobileNotifier and turn Alert Dashboard to on. Also, the Alert Dashboard only shows if you have notifications.

**Comment by Santonio84** [comment]
Thnx a lot! I though it always shows even when there are not notifications.

Thnx again.
