### ISSUE TITLE
BATTERY DRAIN

### ISSUE THREAD

**Issue by psaik77** [peterhajas/MobileNotifier#299]
Hi, I just installed MobileNotifier Beta 5 yesterday. After charging my phone overnight...i found my phone had gone from 100% to around 20% in a matter of hours. Even plugging into a car charger would keep draining the battery instead of charging. After uninstalling the app, the problem was fixed. 

Please let me know if others have this issue and if it will be fixed in a future release.

Running on Iphone 3g with iOS 4.2.1

**Comment by timnovinger** [comment]
I do not know of any others who are having this issue.

**Comment by psaik77** [comment]
it is possible it could be due to something else. Will try a few things and keep you posted. 
Btw, is there a new update coming out soon?

**Comment by psaik77** [comment]
It seems as if it is caused by something else. My Apologies.

**Comment by timnovinger** [comment]
Good to hear, thanks for the bug report.
