### ISSUE TITLE
Lock screen bar shows up in apps

### ISSUE THREAD

**Issue by ifonefox** [peterhajas/MobileNotifier#31]
When you open the MobileNotifier "dashboard" on the lock screen via activator and select an app, when that app loads, the MobileNotifier unread bar from the lock screen is still visible.

**Comment by n808** [comment]
Same problem, showed up in beta3r6 for me. In many cases, I can not get rid of the lock screen bar at all, and it stays in front of everything until I respring. Screenshot:
http://i.imgur.com/T1vcR.png

**Comment by peterhajas** [comment]
Are there various steps that you can detail to reproduce this issue?

Thanks!

Peter

**Comment by n808** [comment]
Sorry for the late reply - notification went to rarely used e-mail... The problem has gone away for me.
