### ISSUE TITLE
Cant download from cydia*

### ISSUE THREAD

**Issue by rayzorboriqua** [peterhajas/MobileNotifier#33]
i downloaded for my iphone with no problems what so ever. But when I tell any of my friends to download it, doesn't seem to work. They get a page that says the requested modifications cannot be applied due to required dependencies or conflicts that cannot be automatically found or fixed. She hasnt downloaded anything but 3 themes. so there really isnt anything to interefere with the install.

**Comment by peterhajas** [comment]
They need to get Activator and PreferenceLoader.

**Comment by rayzorboriqua** [comment]
thank you it worked. Love the beta so far. keep up the good work, the finished product will be amazing. Lets hope apple doesnt come steal your code and call it THEIR innovation for ios 5 haha.
