### ISSUE TITLE
ISSUES WITH ALARMS AND SKYPE

### ISSUE THREAD

**Issue by anupjohnmani** [peterhajas/MobileNotifier#34]
I have been using mobile notifier since yesterday.Gotta say incredible work by you and your team...I would like to highlight a couple of issues that i found very frustrating.

1) ALARM: The notifier informs me of the alarm but somehow the snooze or the stop options are not coming anymore. When i tap open on the notification it simply takes me to the clock app but still couldn't stop the alarm. Eventually had to re-spring the phone to stop it.

2) SKYPE: When receiving calls on skype upon opening the notification i am able to answer the call but the ringing keeps continuing in the background...found the same issue with yahoo messenger on calls..

**Comment by glaszig** [comment]
second that. the alarm clock bug is really anoying ;)

**Comment by lewc** [comment]
3rd'ed Alarm should really be high priority to get fixed

**Comment by ahti** [comment]
same here, good thing i had just installed sbsettings or i would've had to completely reset the phone

**Comment by ghost** [comment]
Just experienced the alarm bug myself. Also opened another issue up regarding it, didn't see this one... whoops.

**Comment by ryangball** [comment]
You can get an app called "Respring" in Cydia. When your alarm goes off, just tap that app and it will go off.

**Comment by glaszig** [comment]
@ryangball you must be kidding us ;)

**Comment by ryangball** [comment]
If you want to continue using MobileNotifier, and want a work around for the bug, then do that. It's the easiest work around. I'm sure the Dev will look into this but he's probably got other stuff going on as well.

**Comment by peterhajas** [comment]
The alarm bug was fixed, update in Cydia.

Skype issue fix coming soon...

**Comment by lewc** [comment]
Brilliant, reinstalling now!

**Comment by peterhajas** [comment]
Skype issue fixed! It'll be out in the next release

https://github.com/peterhajas/MobileNotifier/commit/f31779a9a036a3d92f337fb1348cb44c28b5b682
