### ISSUE TITLE
Clock App Alarms

### ISSUE THREAD

**Issue by ghost** [peterhajas/MobileNotifier#39]
When my alarms go off, MobileNotifier doesn't alert properly and also hijacks Apple's default notifier for the alarm. The result is the inability to snooze or turn off the alarm. Only way I could get the alarm to shut off was to re-spring the phone. 

I am running JB'd iOS 4.2.1 on an iPhone 4.

**Comment by omagus** [comment]
Yes i have the same problem, When ever I set an alarm it goes off but you can click the snooze button anymore as it does not responded to the top lock button, also when you have the timer active and the phone on lock, the alarm will go on constantly only way to slove it is either click on the iPod or turn off the phone/re-spring.

**Comment by Lexis** [comment]
There was an update a few hours ago which should fix this.

**Comment by peterhajas** [comment]
This has been fixed in beta3r5, update in Cydia.

**Comment by omagus** [comment]
Thanks works like a treat!
