### ISSUE TITLE
Slide down thing on lock screen

### ISSUE THREAD

**Issue by arsenm** [peterhajas/MobileNotifier#4]
Whenever I lock the phone, the slide down thing appears. However, if I make that go away and then shutoff the screen, it doesn't come back next time I go to unlock the phone. It reappears on an actual re-locking.

**Comment by peterhajas** [comment]
This will be fixed in an upcoming release - I have a new display for the lockscreen that will launch soon.

**Comment by peterhajas** [comment]
This is no longer the case.
