### ISSUE TITLE
FEATURE REQUEST: Add a "Forget" button

### ISSUE THREAD

**Issue by jayt** [peterhajas/MobileNotifier#40]
Please add a "Forget" button or "Mark Read" button to the choice of "Later" and "Open". The way your product currently works the only way to actually dismiss an item is to "Open" it. That's actually more bother than the current system. Many of the alerts are simple enough that I don't need to go to the program, I just want to acknowledge it and move on. This is a great start to a better notification system. If you don't do it this way, you should have some other way to delete or dismiss notifications.

**Comment by targit86** [comment]
I was going to request the same thing. Add a "Dismiss" button, along with a an "Expand" button which will show all of the content of the notification (i.e. the entire SMS).

So the buttons would be: "Dismiss", "Expand", "Later", "Open"

**Comment by tap52384** [comment]
I would suggest that in the settings that you could specify what the behavior will be.  For example, you may want swiping away notifications to save them for reviewing later, while tapping on a notification will giving you the choice to forget or open.
Expand is a great option as well.

**Comment by eaferrari24** [comment]
I personally think that a swipe should be later (it shows an exerpt); if you tap it, the full message is shown, with the options to "dismiss" and "open". I don't feel like there would be any reason to have a later button, it would just be extra clutter IMO

**Comment by btaroli** [comment]
With additional buttons, might need to switch them to icons instead...

**Comment by simonchunk** [comment]
Yep, I get annoyed by this also. I'd personally be much happier if the options were simply tap to get the options of 'Forget' and 'Open', then the pending alerts would simply hold a memory of what the notification was, regardless of my choices. Example: I get a FaceBook notification, I read it from the pop-up and 'Forget' it as I do not want to reply. I can then however, open the current pending alert menu and still see that original alert, it simply moves down the list as new alerts occur. The list could cache, i don't know 50-100 alerts.

**Comment by btaroli** [comment]
I think the need for this has been reduced since the app-based cleaning of notifications has been added. Might still be handy, but not nearly as necessary as before.

**Comment by tap52384** [comment]
Instead of a forget button, swiping to forget would be best. I have
noticed that swiping away alerts no longer works...

Sent from my iPhone

On May 24, 2011, at 8:54 PM, btaroli
reply@reply.github.com
wrote:
