### ISSUE TITLE
Alarms fail to stop

### ISSUE THREAD

**Issue by boxingcow** [peterhajas/MobileNotifier#41]
Impossible to stop alarm unless you go to 'Clock' and delete the alarm.

**Comment by tinifni** [comment]
This issue has been closed. Update to beta3r5 in Cydia. See: https://github.com/peterhajas/MobileNotifier/issues/closed/#issue/39/comment/823454

**Comment by boxingcow** [comment]
Oops. Sorry. Thanks.
