### ISSUE TITLE
Remove all notifications for an app when starting it

### ISSUE THREAD

**Issue by mikeash** [peterhajas/MobileNotifier#42]
I run into this with AIM. Somebody sends me about 30 messages which show up as notifications. I then use one notification to open the app. MN still keeps all 29 remaining notifications around, though, requiring a laborious process of deleting them all. It would make sense, I think, to delete all notifications from a particular app once that app is started.

**Comment by ahti** [comment]
+1 for this one, also not only when started with alerts/alertdashboard, but when started from multitasking-bar or homescreen also (if possible)

**Comment by G12c4** [comment]
Agree +1 its anoying to clear the dash every time u get a load of messages in whatsapp, facebook or im+, etc.

**Comment by peterhajas** [comment]
Should this remove based on Sender? Or app?

i.e. This makes sense for Facebook, but for Messages you might only want the sender.

**Comment by ahti** [comment]
I think in most cases removing all notifications by the app makes more
sense, so this should be default behaviour, you could however add
exceptions
(maybe you cold provide a doc for how to add those exceptions so as
many apps as possible get custom and thereby better behaviour)
(wether the default is used or not if no specific action is specified
could even be added as an option toggle)

**Comment by btaroli** [comment]
I think one is done now, right?

**Comment by mikeash** [comment]
Seems to be. In any case, MN is certainly working the way I expect it to now. Are there any missing subtleties or corner cases that I haven't seen which are keeping this open, perhaps?

**Comment by timnovinger** [comment]
This issue was fixed in [this commit](https://github.com/peterhajas/MobileNotifier/commit/95032a5a1a28ef8dafb923ca720d10f1d753d902).
