### ISSUE TITLE
Allow disabling of MN notification sound

### ISSUE THREAD

**Issue by mikeash** [peterhajas/MobileNotifier#43]
MN seems to play its own sound, in addition to the push notification sound played by the system. This is not exactly what I'm after. I'd like to disable MN's own sound entirely and just let the system do what it usually does.

**Comment by Override79** [comment]
I agree with that, I am using MyProfiles application to change and disabled sound based on time, but right now I have no way to disable MN sound.  Right now I am hearing 2 seperate sounds and 2 vibrations with some delay.

**Comment by btaroli** [comment]
Agreed. It would be nice to be able to hear the sounds, which differ by application, rather than have them all overriden by one. This way I can differentiate what kind of event is coming in when I can't see the phone (e.g. in holster).

**Comment by Kingfish** [comment]
Agreed as well.  I'm hearing two sounds at once which is annoying and confusing.  A toggle to turn off MN's tri-tone sound is what's needed here.

**Comment by peterhajas** [comment]
This has been fixed - https://github.com/peterhajas/MobileNotifier/issues/72 - thanks for filing it!

**Comment by mikeash** [comment]
Fantastic! This was the one thing stopping me from using MN for real. Just installed it, and it's looking (and sounding) great.

**Comment by Kingfish** [comment]
Thank you Peter.
