### ISSUE TITLE
MobileNotifier band doesn't respond to interaction on lock screen

### ISSUE THREAD

**Issue by BrakTalk** [peterhajas/MobileNotifier#45]
When my phone loads the lock screen, I see the MobileNotifier with an ever increasing amount of notifications indicated but when I "tap", "swipe" or whatever gesture, it doesn't respond. 

Here is the screenshot of what I'm referring to:  http://screencast.com/t/nnqNd1kReT

The notifications that appear while the phone is not locked appears to work fine however I'm still learning the ins and outs of it.

**Comment by OneThatWalks** [comment]
I believe the lockscreen notification is just like the way apple did it.  You are unable to interact with it you have to unlock to interact.

**Comment by peterhajas** [comment]
This is not an issue, the lockscreen is not an interactive element.

**Comment by peterhajas** [comment]
This is not an issue, the lockscreen is not an interactive element.

**Comment by BrakTalk** [comment]
Might want to talk to the folks at Intelliscreen as I can interact with the lockscreen with their app. (double tap and scrolling are both enabled on the lockscreen).

**Comment by mellomike** [comment]
I also see this as a bug. Maybe if the MobileNotifier UI was positioned right on top of my clock it wouldn't be an issue. But lock screen UI for MobileNotifier is kinda distracting in it's current implementation.

**Comment by peterhajas** [comment]
Hi there, let me clarify what I said about this issue, as it's possible that it could be misinterpreted. I responded hastily, as I am (obviously) faced with a lot of issues and comments every day.

The lockscreen, in the intention of the iPhone, is not meant to be an interactive element. Nothing on the stock device allows for interaction other than the "slide to unlock" bar at the bottom of the device. This is how I would like to keep MobileNotifier.

I understand other tweaks do allow interaction with the lockscreen, this is not a technical issue with MobileNotifier so much as it is a usability one. The previous beta, Bountiful Bran Flakes, allowed for lockscreen interaction, and the response I got from users was overwhelmingly negative. 

To add to this, it's difficult to reliably talk to the sleep timer on the phone, especially when it's something to do with the lockscreen. Should I keep the phone alive until you're done touching elements? How long? 10 seconds? What if you're still looking at something? You can only imagine how much more confusing this will be once people start putting phones in their pockets. What if a button gets pushed and the phone thinks there's interaction from something in your pocket (like metal, which sets off the capacitive touch sensor)? What happens then?

Overall, these issues made me switch to a much more minimal lockscreen display for MobileNotifier. If there's something I'm missing about interaction on the lockscreen (what would you like it to do?) then I'm more than happy to take a look at it.

I'll also be adding an option soon to allow for hiding of the lockscreen view for MobileNotifier, and publishing the specification I use for alert storage. If someone would like to make a super-awesome ultra-interactive enhancement to the lockscreen, they're definitely free to do so. I have open source code, and soon I'll be clarifying the interfaces into MobileNotifier. I'm committed to this.

Again, let me know if there's something I missed or something that wasn't clear in my replies here.

**Comment by muiqo** [comment]
imo this would be a killer feature! just make the notification-button expand with a slide- instead of a touch-gesture and voila – the list could be interactive again. default sleeptimer and the power-button would reset everything to normal + turn off screen.
