### ISSUE TITLE
My ideas for the UI

### ISSUE THREAD

**Issue by to86** [peterhajas/MobileNotifier#48]
From the noticeable attention mobile notifier has got, i have noticed people either love it or hate it. Most of the criticism stems from the UI, however most of those criticising it are not doing anything constructive to help. So I thought  Iwould convey my ideas to see what you and others thought.

Right now the bar comes over the top line of icons, or the top part of the app rendering it useless. To combat this i was wondering if you could implement the notifications via the flashing bar that comes up when the phone is tethering, or when we are in a call. Could you do a similar thing for notifications, maybe in red? So you could have the latest notification continue to flash there until it was read. The benefit would be there even though it remained it would not interfere with the app, as iOS resizes when one of those bars come up. If multiple notifications came in you could show the latst and then it would change to 'x pending noritifications' until we bring up the alert dashboard and clear it. 

I don't know how feasible this is but I felt it was a good idea and would be far less obtrusive and a lot more native. What do you think?

**Comment by Jayke** [comment]
I like this idea, as the OS, like you say already handles these kind of notifcations properly, but I feel that red wouldn't be the best choice of colour, I'd like a notification to notify me (evidently) but not throw it in my face with a red flashing box.

**Comment by to86** [comment]
Ye fair enough, maybe not a red bar, but you get the idea. Colour isn't so important, its just designing it in that manner. I feel it would be a lot more native, and a lot less obtrusive than how it looks at the moment.

**Comment by ahti** [comment]
nice idea :) (maybe make this optional for there always are ppl who dont like sth and it would be wasting code to throw away the old notification style)

**Comment by kristianpennacchia** [comment]
I think I'll bump this.
The current double height notification bar in use in beta4 looks good, but I feel that it would seem more natural, more iOS and Apple like if it used the double height status bar looks that Apple utilizes.

An example: http://xe3.xanga.com/db7f221171733246421467/z195370203.png & http://iphonegeartalk.com/wp-content/uploads/2011/01/1295871643-17.png

That in maybe green (customisable?) would fit perfectly in my opinion.
