### ISSUE TITLE
Bug report: Clear AlertDashboard 

### ISSUE THREAD

**Issue by aniceberg** [peterhajas/MobileNotifier#49]
If you bring up the "Clear AlertDashboard " dialog, and then press the home button, the dialog will stay frozen on your screen and not allow any touch or button input to clear the dialog, effectively locking your phone. The only way to correct it, is to reset your phone (holding Home & Power for 10 seconds).

**Comment by peterhajas** [comment]
Just fixed this issue! Thanks for submitting it!

https://github.com/peterhajas/MobileNotifier/commit/5bfdd4a652017032c6af7138ac36bb491c2c1b47
