### ISSUE TITLE
FEATURE REQUEST:  MobileNotifier does not respond to input on lock screen

### ISSUE THREAD

**Issue by BrakTalk** [peterhajas/MobileNotifier#50]
I am recreating this issue as there is no option to re-open.  The reason for doing so is the resolution to the previous does not sufficiently explain why this feature is not implemented.  I believe the author incorrectly states that the lock screen can not have interactive elements.  I believe this is incorrect as there are other apps that do allow for interaction on the lock screen (namely, IntelliScreen with it's tap and scroll events).

Therefore, I have reclassified this as a feature request:

When my phone loads the lock screen, I see the MobileNotifier with an ever increasing amount of notifications indicated but when I "tap", "swipe" or whatever gesture, it doesn't respond.

Here is the screenshot of what I'm referring to: http://screencast.com/t/nnqNd1kReT

The notifications that appear while the phone is not locked appears to work fine however I'm still learning the ins and outs of it.

**Comment by mellomike** [comment]
I'm giving a +1 on this issue also.
