### ISSUE TITLE
MN and Android Lock XT

### ISSUE THREAD

**Issue by tquach-zz** [peterhajas/MobileNotifier#51]
When using AndroidLock XT and MobileNotifier , if you click on Open this bypasses the Android Lock and allows access to the phone.

**Comment by 9Life42** [comment]
I have the same problem. I think it would be better to remove the standard gray overlay from the lock screen and only allow the black notification box to appear (with the number of unread notifications). If you want to see the notification while it's locked then just swipe the way you used to. Having the gray box appear and cover the clock and also bypass the swipe to unlock doesn't seem he best way to do it.

**Comment by peterhajas** [comment]
This has been fixed - release coming soon!
