### ISSUE TITLE
Expandable Preview

### ISSUE THREAD

**Issue by 9Life42** [peterhajas/MobileNotifier#55]
It would be great to be able to expand the preview of the notification so that one can read all of it without opening the app. Perhaps the notification could scroll or have an expand option. It would be nice to have the same functionality at the lock screen when there are multiple pending notifications. As it is, you can tell that you got another notification, but not where it came from or what it says without unlocking the phone and opening the app.

**Comment by G12c4** [comment]
+1 like :)

**Comment by Gidgidonihah** [comment]
Ditto. Really wish I could see all of the notification. Some apps (like ESPN) don't even have a useful way to find what was notified if I can't read the whole message.

**Comment by btaroli** [comment]
+1
