### ISSUE TITLE
Doesn't display icon for any notifications on 3GS.

### ISSUE THREAD

**Issue by Jayke** [peterhajas/MobileNotifier#56]
I'm using an iPhone 3GS, running 4.2.1 and the notifications seem to work very well, apart from an issue where none of my notifications seem to be displaying the icon of the app they were sent from.

E.g. I get a text message, notification is displayed, but there is no SMS app icon displayed, just an empty space, same applies for other apps that I receive a notifcation from such as Facebook..

Is this an issue specifically to the 3GS? As I haven't heard of many people reporting this besides myself.

Many Thanks

**Comment by eaferrari24** [comment]
Same thing happens to me on a 3GS 4.2.1
Not sure about Facebook, but SMS has the problem for sure. However others such as ESPN show the icon.

I also have an issue with skype and getting phone calls = crash and push from skype = crash

**Comment by Jayke** [comment]
The Facebook one seems to be displaying fine for me now, perhaps it was just a one off!
But definitely no app icon for SMS, which is the most common kind of notification I get and it would be nice to tell it's a text just from a quick glance.

**Comment by timnovinger** [comment]
This issue has been fixed in later builds.
