### ISSUE TITLE
BUG: MN Crashing Springboard

### ISSUE THREAD

**Issue by fgblomqvist** [peterhajas/MobileNotifier#57]
I recently installed MobileNotifier and now my SB is crashing everytime I recieve an notification. I read in the comments on your page that another guy also has this bug. I have an iPhone 3G on 3.1.3/whited00r 4.2. The other guy also has 3.1.3 so maybe that is the error?

**Comment by WG5516** [comment]
I have an iPod 3G running on 4.2.1 and I'm experiencing crashes every time I receive a SMS via my Line2 app. It was working great before the update this week.

**Comment by fgblomqvist** [comment]
Why did this got rated as Unusable?

**Comment by WG5516** [comment]
Because you're not able to "use" the app as intended with our issue. That's what I'm guessing... _shrugs_

**Comment by fgblomqvist** [comment]
yeah really (no irony here)
