### ISSUE TITLE
3.1.3 Crashing

### ISSUE THREAD

**Issue by exiva** [peterhajas/MobileNotifier#59]
I emailed you about this bug, Peter but I figured I'd open a real issue here.

Mobile Notifier crashes on Notifications as well as the pending panel.

Notification crash:
    Mar  1 04:37:33 Travis-La-Marrs-iPhone CommCenter[29]: removing received message 2147483648
    Mar  1 04:37:33 Travis-La-Marrs-iPhone SpringBoard[54]: At MNAlertManager! Delegate: <PHACInterface: 0x3c28120>
    Mar  1 04:37:33 Travis-La-Marrs-iPhone SpringBoard[54]: **\* -[UISwipeGestureRecognizer setNumberOfTouchesRequired:]: unrecognized selector sent to instance 0x29f260
    Mar  1 04:37:33 Travis-La-Marrs-iPhone SpringBoard[54]: **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[UISwipeGestureRecognizer setNumberOfTouchesRequired:]: unrecognized selector sent to instance 0x29f260'
    Mar  1 04:37:33 Travis-La-Marrs-iPhone SpringBoard[54]: Stack: (\n    843263261,\n    825818644,\n    843267069,\n    842763033,\n    842725440,\n    5960056,\n    844154820,\n    5957420,\n    5950852,\n    6064356,\n    658153,\n    863155673,\n    842986769,\n    863146419,\n    829307061,\n    829306617,\n    842761911,\n    842986769,\n    843026401,\n    829400001,\n    829355499,\n    829356301,\n    829353587,\n    838566129,\n    843011371,\n    843009055,\n    860901832,\n    843738160,\n    843731504,\n    14371,\n    13596\n)
    Mar  1 04:37:33 Travis-La-Marrs-iPhone com.apple.SpringBoard[54]: terminate called after throwing an instance of 'NSException'
    Mar  1 04:37:37 Travis-La-Marrs-iPhone ReportCrash[68]: Formulating crash report for process SpringBoard[54]
    Mar  1 04:37:38 Travis-La-Marrs-iPhone com.apple.launchd[1](com.apple.SpringBoard[54]): (com.apple.SpringBoard) Job appears to have crashed: Abort trap

Pending Panel crash:
    Mar  1 04:41:20 Travis-La-Marrs-iPhone SpringBoard[78]: **\* -[UIActionSheet showFromRect:inView:animated:]: unrecognized selector sent to instance 0x45bde40
    Mar  1 04:41:20 Travis-La-Marrs-iPhone SpringBoard[78]: **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[UIActionSheet showFromRect:inView:animated:]: unrecognized selector sent to instance 0x45bde40'
    Mar  1 04:41:20 Travis-La-Marrs-iPhone SpringBoard[78]: Stack: (\n    843263261,\n    825818644,\n    843267069,\n    842763033,\n    842725440,\n    5968540,\n    843020431,\n    844097412,\n    844097260,\n    844097204,\n    844096268,\n    844099468,\n    844093696,\n    844091284,\n    6629963,\n    844072848,\n    844071060,\n    860907492,\n    843011371,\n    843009055,\n    860901832,\n    843738160,\n    843731504,\n    14371,\n    13596\n)
    Mar  1 04:41:20 Travis-La-Marrs-iPhone com.apple.SpringBoard[78]: terminate called after throwing an instance of 'NSException'

**Comment by peterhajas** [comment]
Thanks for this! I've flagged it as necessary for me to fix before the next release!

**Comment by exiva** [comment]
Thanks for making it a priority. I know most people wouldn't bother since 3.1.3 is pretty much dead.

If you need testing before the release let me know, I'd be glad to test it out on my 2g.

**Comment by peterhajas** [comment]
I _think_ I fixed this issue with this commit:

https://github.com/peterhajas/MobileNotifier/commit/8489ae0ef436f71d405f79f42a8ba7b3a340f5b5

If you could email me (peterhajas@gmail.com) with "3.1.x tester from GitHub" as the subject (or something similar), I'd love to email you the build to test out?
