### ISSUE TITLE
A few issues I have noticed

### ISSUE THREAD

**Issue by to86** [peterhajas/MobileNotifier#6]
Ok so I have been using mobile notifier for a few days now, and just thought I would add in what I feel is lacking:

1) landscape support - i am sure u are aware of it so I won't harp on about it.

2) If i get a notification that contains a large amount of text the notification simply adds in '...', and renders it useless, because I can't read the sender or any part of the message. Would it be possible to allow the text to go onto two separate lines?

3) This is more a request than an issue. When you get multiple notifications you only show the latest. I understand you don't want the notifications taking over our whole screen, but is there a way you could still remind us there is a notification. I was thinking something along webos lines, for the touch pad. Where we can cycle between the notifications, is that going to be difficult?

Right now those are the only things to complain about ,which i find amazing for a beta. Great work, and I look forward to future versions!

**Comment by peterhajas** [comment]
1) Yep! I am aware of the lack of landscape support. It'll be added soon - Kyle has sent me the graphics, they just need to be implemented.
2) I have a few ideas floating around for how to deal with this, stay tuned!
3) For receiving multiple notifications, they'll replace the older one. If there are new pending ones, you'll see in the statusbar. Some webOS-type functionality is definitely interesting, and we'll explore those options.

Thanks for the input! Wait until you see what's coming soon. It's not in the Cydia repo yet, but it is on GitHub. It's going to blow some minds.

**Comment by to86** [comment]
I have also noticed a problem with the active dashboard. Its not working well at all. For example if i click on a twitter notification, it might open mail. If i click on an SMS, it might open whatsapp!

Also is there a chance you could enable dashboard to open whenever we bring up the switcher bar. I know we can enable this using activator, but that replaces the switcher bar completely. I was hoping both could come up at the same time? is this possible?

**Comment by peterhajas** [comment]
So, the dashboard is in a very early stage. I have development versions of the dashboard that are in testing that work as you describe - open with the switcher, above the apps that are multitasking. It works significantly better. I hope to have this ready for release soon.

**Comment by verheyenkoen** [comment]
+1 for point 2

**Comment by thunder-kt** [comment]
hey, can u put in a setting that let me turn off the use idevice while syncing, please, i hate that feature, other than that, great mod

**Comment by thunder-kt** [comment]
hey, can u put in a setting that let me turn off the use idevice while syncing, please, i hate that feature, other than that, great mod

**Comment by thunder-kt** [comment]
hey, can u put in a setting that let me turn off the use idevice while syncing, please, i hate that feature, other than that, great mod
