### ISSUE TITLE
Quick Reply Support

### ISSUE THREAD

**Issue by peterhajas** [peterhajas/MobileNotifier#61]
This would be experimental at first (probably not add itself to "sent" messages right away) but would work. Thoughts?

**Comment by exiva** [comment]
Quick Replying would be a great addition. Upvoted.

**Comment by ahti** [comment]
a reply button under the later and open button for sms messages which then transforms to a text field with the enter-ish-button on the keyboard saying send ... would be quite cool

**Comment by peterhajas** [comment]
I deleted a comment which only advertised another tweak here, one that is not free nor open source (banner ads are not something I would consider "free").

MobileNotifier, regardless of whether or not you use biteSMS, will have QuickReply functionality built in.

**Comment by Kingfish** [comment]
Apologies to the developer.

**Comment by to86** [comment]
Ye if you can have native quickreply support that would be great. I would rather that than have to have a separate tweak like bitesms installed. Have you considered quickreply for other apps, say mail?

**Comment by timnovinger** [comment]
This feature was added in later builds.

**Comment by to86** [comment]
Yes and it works great. Any plans to implement landscape mode?
