### ISSUE TITLE
activators options

### ISSUE THREAD

**Issue by highdecibels** [peterhajas/MobileNotifier#64]
please add support to choice how to view the notifications windows thing as would be better it not coming up everytime you double tap..
also I use a tweak called vibracations could add support for that also so I can change the vibrate pattern for my notifications

**Comment by peterhajas** [comment]
We already have Activator settings, please use the Activator section in Settings and choose MobileNotifier.

"Vibracations" is not a tweak that I'm interested in, but I'll look into it.

**Comment by highdecibels** [comment]
ye I noticed it is already a option but when u pick a different option to activate it everytime you double tap it still comes up I woule like to change the option all together. n vibractions yes u mite use it but I do as havey phone on vibrate alot so it gud to make the vibrate more intenses so you acatally notice it lol thanks for the help
