### ISSUE TITLE
Calendar notifications with Snooze option

### ISSUE THREAD

**Issue by Gbouck** [peterhajas/MobileNotifier#65]
I understand that calendar notifications are on their way to being implemented. This request is to have an option to Snooze them. Similar functionality to desktop email programs and other smart phones. It could be preset time options, or it would be radical to also have a custom time option. And then when that time had elapsed, MobileNotifier pops up with the same notification before.

**Comment by bokahrij** [comment]
I don't know if this will work when mobilenotifier gets the calendar update, but Gbouck you should try "RemindMeLater" from Cydia. I use this and it and it allows for a snooze button on the pop up and the delay is configurable from the settings app.

**Comment by timnovinger** [comment]
Sorry, but a snooze feature is not planned. Calendar alerts have been implemented in later builds.
