### ISSUE TITLE
Turn off using the iDevice while syncing!!

### ISSUE THREAD

**Issue by thunder-kt** [peterhajas/MobileNotifier#68]
I know it a great feature but i hate it, is there a way to turn it off, like before the latest update?

**Comment by peterhajas** [comment]
What do you mean?

**Comment by thunder-kt** [comment]
you added a feature to the mod that let me use the ipod while i sync it with itunes, i want to disable that feature

**Comment by peterhajas** [comment]
Fixed, will be pushed out in a release soon.

**Comment by thunder-kt** [comment]
alright, thank you
