### ISSUE TITLE
SB crash on Incoming Viber Call

### ISSUE THREAD

**Issue by aniceberg** [peterhajas/MobileNotifier#69]
Springboard crashes when I get incoming Viber calls, which I suppose is due to Viber's use of the notification API to get user input to either dismiss or accept the incoming call. The incoming call notification also plays a Viber-specific ringtone. When it comes back, MobileSubstrate gives me the apology window to either exit or restart SB.

Did anyone else notice this issue?

I suppose the next step is to put app exclusion toggles in the settings panel, (which I'm guessing is already in the works.)

**Comment by peterhajas** [comment]
Fixed - a release is coming soon with this fix included!
