### ISSUE TITLE
Bug on Skype

### ISSUE THREAD

**Issue by b0ywarrior** [peterhajas/MobileNotifier#70]
the first i would say thx to Peter Hajas for fixing many bugs include my alarm bug found.
Now another new bug i've just found on Skype :
When I've got a voip call via Skype, when I select Open from Notification Bar, the voip skype call connect but the Ringring Sound still continue due the talking conversation.
So i have to drop the call and call them back !

**Comment by peterhajas** [comment]
https://github.com/peterhajas/MobileNotifier/commit/f31779a9a036a3d92f337fb1348cb44c28b5b682

Fixed for next release, thanks for your kind words!
