### ISSUE TITLE
Lockscreen view covers clock

### ISSUE THREAD

**Issue by olllen** [peterhajas/MobileNotifier#71]
Title basically says it all, in the screenshots of MN the lockscreen notification shows up below the clock but on my phone it sits on top of the clock, right below the carrier/wifi/battery stripe. On 3GS, 4.2.1. Otherwise great stuff, looking forward to the updates!

**Comment by peterhajas** [comment]
Fixed in the most recent two commits
https://github.com/peterhajas/MobileNotifier/commit/937079267388094c646dc61b6539fc4feeb2d032
https://github.com/peterhajas/MobileNotifier/commit/0425f71d529c900f9f8efd2f928a9cc9eb07e313

This will be included in the next release!
