### ISSUE TITLE
Alert Sound

### ISSUE THREAD

**Issue by gamemasta0** [peterhajas/MobileNotifier#72]
I'm sure you have seen this before, but the alert sound is the default 'tri-tone' sound for all alerts. I don't know how difficult it would be to implement the usage of the sounds that are normally set for those alerts but I think it would be nice if it did that so I could discriminate what kind of alert I'm receiving (and perhaps who's phone just received the alert, given the wide usage of tri tone). This appears to be something to implement in the MNWhistleBlowerController in the alertArrived method. Perhaps you can gather from the system what alert is supposed to be played and play that rather than a hardcoded system sound for every alert. I'm not going to pretend I know how hard that would be to do, but if that's easy/possible that would be nice. Thanks!

**Comment by btaroli** [comment]
I would prefer the option of turning OFF MobileNotifier's sound, since having one sound for /all/ notifications is annoying to me. I would like to hear the sound I have assigned via each app for which alerts are occurring instead.

**Comment by Kingfish** [comment]
Agree with btaroli.  The tri-tone playing on top of the specific app sound is annoying.  A toggle to turn off MN's tri-tone so all we get is the different default app sounds is what's needed.

**Comment by cobrabr** [comment]
Just chiming in to agree with btaroli and Kingfish -- MobileNotifier is awesome, but the fact that it plays a sound regardless of my settings for each application is a show-stopper for me (I don't necessarily want everyone around me to know I'm chatting on my phone instead of working, for example :D).

Would it be possible to give us the option of turning the sound off?

**Comment by ches** [comment]
Chiming in here with my +1 since voting isn't possible anymore in the new GitHub issues -- I've been patient for nearly as long as I can -- I love MobileNotifier generally, but not being able to disable the omnipresent sound is pretty much a show-stopper for me too. It's really a shame for me that this still hasn't been addressed.

**Comment by btaroli** [comment]
Honestly, I don't know why there simply hadn't been an optionto turn
off MN's sound. Why does it even need to do this? Every event type it
captures does already generate their own sound or allow to disable it.
Seems unnecessary to add it here, and needlessly complicates things.
:-(

On May 13, 2011, at 7:57, ches
reply@reply.github.com
wrote:

**Comment by peterhajas** [comment]
I'm actively working on this, I think I'll make push notifications just not sound the tritone. I'm still conducting tests to make sure this works in every situation.

**Comment by ches** [comment]
Yes, just disabling MN's sound is what I really meant @btaroli -- realized a moment later I should have commented on #12 instead which is more directly on that subject.

Thanks for your work Peter! I didn't mean to sound whiney about something you're giving away for free.

**Comment by peterhajas** [comment]
Fixed this issue! Will be pushed out in beta4r1!

And don't worry about it @ches :)

**Comment by ches** [comment]
Sweet! Thank you :-)

**Comment by Kingfish** [comment]
Thank you Peter.  This was the one thing keeping me from using your tweak.  Now I will be able to install and check it out fully.  Keep the improvements coming!  :)

**Comment by cobrabr** [comment]
Awesome! Going to grab it right now!

Thanks a bunch, Peter!

**Comment by cobrabr** [comment]
Quick question, Peter: is it possible to add an option to switch the vibration off when receiving notifications?
