### ISSUE TITLE
Remove old notifications automatically

### ISSUE THREAD

**Issue by muhlba91** [peterhajas/MobileNotifier#73]
At first, I must say that your way of notifications is genious and great.
However, is it possible to remove "old/seen" notifications from the AlterDashboard automatically? For example: I have LockInfo installed, so there are no PopUps when the device is locked. I receive a SMS and after unlocking no nice notification via MobileNotifier gets displayed. So I click on the messages app and read the SMS. The main thing here is that this notification doesn't get removed from the AlertDashboard. :-(

**Comment by sNick86** [comment]
When lockscreen is active i eigther don't get a notification.

**Comment by btaroli** [comment]
I think I have seen this working as you describe in b4r1. Whether you tap the notification in the list or open the app directly, the notifications for that app are removed from the list.

**Comment by muhlba91** [comment]
yeah, it is working now! :-)
