### ISSUE TITLE
Issues with LockInfo

### ISSUE THREAD

**Issue by bigoats** [peterhajas/MobileNotifier#75]
MobileNotifier doesn't seem to work at all with Lockinfo and/or Popup blocker. Both Lockinfo and Popup blocker are installed along with Mobilenotifier. Not getting any notifications at all from mobilenotifier however lockinfo is working just fine. Dashboard doesn't show any notifications either.

**Comment by peterhajas** [comment]
LockInfo compatibility has been resolved - turn off the lockscreen view in settings.

I do not understand your issues with Popup blocker or no notifications on the dashboard. Please make sure you receive notifications alert and send them to "later".

Popup blocker support is not planned.
