### ISSUE TITLE
Lockscreen Conflicts

### ISSUE THREAD

**Issue by ghost** [peterhajas/MobileNotifier#77]
1) When the Alert Dashboard is open and the sleep button is pressed, Alert Dashboard doesn't close.  Upon wake the Alert Dashboard stays over the Lock screen, and over the home screen after swiping to unlock.

2) If a new notification comes in at the lock screen, at least in my 3GS, it shows up first as a normal notification which can be used to bypass the lock.  It only shows up as MobileNotifier (1) after putting the phone to sleep AFTER the notification is received (if I've investigated this correctly).

**Comment by DanweR** [comment]
2) same problem!
