### ISSUE TITLE
MN crashes Springboard upon Installation

### ISSUE THREAD

**Issue by bergertwit** [peterhajas/MobileNotifier#79]
iPhone 4, running 4.2.1

MobileNotifier worked for about a week, and one morning I woke up to an endless loop of springboard crashes until I uninstalled it. 

I have added no tweaks/mods/hacks/cydia apps since installing MobileNotifier.  I have also sent a syslog to peterhajas@gmail.com

**Comment by peterhajas** [comment]
Have you tried installing the latest release?

**Comment by bergertwit** [comment]
Thanks for getting back to me.  I found the problem was solved when I went into iFile and deleted all instances of mobilenotifier, and then installed it fr scratch. Works like a charm. 

Thanks again,

George Berger
@bergertwit
