### ISSUE TITLE
Support for Music Control Pro

### ISSUE THREAD

**Issue by bweb79** [peterhajas/MobileNotifier#8]
Would love to see support for the Music Control Pro volume/brightness bar in the multitasking switcher view. I use this a lot, so I'm going to have to uninstall MobileNotifier until I can access those controls.

Music Control Pro is by Paul Griffin. http://phoenix-dev.com.

**Comment by peterhajas** [comment]
I have spoken with Paul, and am working on integrating support. I'll leave this open until I do.

**Comment by bweb79** [comment]
Wow, That is great news. Thank you very much. Been playing with the app and have to say it is great. Thanks so much for your hard work.

**Comment by peterhajas** [comment]
This has been fixed, and will be rolled out in the next release.

Thanks so much for your kind words!

Peter

**Comment by bweb79** [comment]
Awesome. I can't wait!!
