### ISSUE TITLE
Notification Pop-ups Disappear Too Quickly

### ISSUE THREAD

**Issue by btaroli** [peterhajas/MobileNotifier#86]
I love that the notifications now have a timeout, but on my iPhone 4 running 4.2.1 they only seem to stay visible for about 5 /seconds/. That's great when I happen to be staring at my phone using something else. But if I've set it down and have to pick it up to see what's there, I scarcely have time to read the note before it vanishes, or I reach to tap on it and wind up tapping on whatever was underneath the pop-up.

I would desire either a longer lag-time (maybe 30 seconds? A minute?). Possibly a configurable option.

**Comment by JoLander** [comment]
I agree.
It should be configurable when to sent the notifcations to later.
Even switch off the timeout entirely should be an option.
If notifications arrive over night, I would like to see them immediately in the morning without researching the Dashboard.

**Comment by bokahrij** [comment]
This would be really good. After the update I didn't really like the pop up disappearing, since I can still use my phone with the pop up, I don't really want it to disappear.

**Comment by peterhajas** [comment]
Fixed, changed the limit to be much higher.

I will add a setting to allow you to specify if alerts should be autodismissed or not.
