### ISSUE TITLE
Ability to "exclude" or "blacklist" certain applications in MN settings.

### ISSUE THREAD

**Issue by Gbouck** [peterhajas/MobileNotifier#89]
It'd be AWESOME if we could "blacklist" certain applications from <b><u><i>seeing</i></u></b> notifications. Like say there's a certain full screen app that I use that if I get a notification on, it interrupts what's going on. So with this option, I could go into the MN settings, and under the "blacklist" add that particular app to it, so that whenever I'm in that app, notifications are disabled temporarily from displaying on top of the screen. But they're still stored in the MN notifications list if I double tap the home button.

Does that make sense?

I'm in love with this app!!!

**Comment by timnovinger** [comment]
Sorry, but this feature is not planned.
