### ISSUE TITLE
FEATURE REQUEST - Activator method also for devices with multitasking

### ISSUE THREAD

**Issue by smeagol152** [peterhajas/MobileNotifier#9]
Hi Peter.
I realize that MobileNotifier does not support Multifl0w (a program to change the native multitasking view). Since there are many users with Multifl0w... what about the activator method also with multitasking devices?

Best regards

**Comment by peterhajas** [comment]
This will be in an upcoming release of MobileNotifier, coming sometime in the next hour or so.
