### ISSUE TITLE
1st Notification Doesn't Show

### ISSUE THREAD

**Issue by j4ckdon4ghy** [peterhajas/MobileNotifier#90]
Iphone 4, 4.2.1, jailbroke with gp. 
Multiple tests of sms notifications reveal that the first notification doesn't show on the lock screen.  If I do not clear the board and send a second sms, the lockscreen will show the appropriate alert. 
When the first sms is sent, the phone is woken up to the lockscreen, but there is no alert from mobilenotification.

**Comment by 9Life42** [comment]
I don't get any notification at all at first either. The phone will vibrate, but I will have to open up the list of pending notifications to see it. If I don't clear the list, it behaves normally, but the first notification after clearing the list doesn't work.

**Comment by alexzielenski** [comment]
Same with me

**Comment by keithchau** [comment]
Same here

**Comment by alexzielenski** [comment]
Fixed in latest update

**Comment by keithchau** [comment]
Yes, confirmed that this is fixed in 0.4r1.  Great job, Peter!
