### ISSUE TITLE
Suggestion: Lockscreen - Multiple Notifications

### ISSUE THREAD

**Issue by DeSiFiEd** [peterhajas/MobileNotifier#93]
I think this needs an entire redesign. Even having the traditional Apple notification system with ability to press "next" would suffice.

Just seeing how many notifications you have isn't too helpful IMO.

Great app nonetheless Peter, appreciate your work.

**Comment by DanweR** [comment]
Hey! Use Activator! i used it for opening a dashboard on the lockscreen! i assigned for doubletap on a clock a dashBoard!!! you should aslo try! easy way to access your msges
