### ISSUE TITLE
No more MobileNotifier notification pop ups

### ISSUE THREAD

**Issue by RM305** [peterhajas/MobileNotifier#97]
I have mobile notifier installed on my iPhone 4 4.2.1 FW. Upon install it was working perfect receiving the MobileNotifier pop-up notifications. I then was forced to restore my phone and then re-jailbreak. After installing all my cydia  packages as I had prior to restoring and using MobileNotifier, I was no longer receiving the MobileNotifier pop-up notifications.I am not sure if MobileNotifier and Tlert has a conflict. Then again before I had to restore I was using the  packages and didn't have any problem whatsoever receiving a pop-up notifications on everything else. The only way to notice of a notification is by double press of  home button and the notifications are on the dashboard.

**Comment by peterhajas** [comment]
This is not an issue with MobileNotifier, but instead, with Tlert.

You cannot use these products simultaneously without error.
