### ISSUE TITLE
A few issues and comments

### ISSUE THREAD

**Issue by warkok** [peterhajas/MobileNotifier#98]
I wanted to let you know about a few issues and comments that I have run into using beta 3 of MobileNotifier.

<ol>
<li>The lockscreen view bar remains on top of the dash when the dash is activated through a activator action on the lockscreen.</li>
<li>The lockscreen music playback controls appear on top of the MobileNotifier lockscreen view bar.  It would be nice if the lockscreen view bar would move down the screen when the playback controls are activated.</li>
<li>I am not sure if this is possible, but it would be convenient if a tap or double tab on the lockscreen view bar opened the dash.</li>
<li>When the dash is activated through an activator action and not the appswitcher it only covers the same amount of the screen as if the appswitcher is open.  It would look much better if the dash covered the entire screen when appswitcher is not open.</li>
</ol>

Thanks for all the hard work, MobileNotifier is looking like a great notification system.

**Comment by tinifni** [comment]
_Regarding number three:_

I have used Activator (in Settings -> Activator) to assign the **Swipe Down** action under the **Status Bar** section for use from **Anywhere** to activate the Dash. This allows activation of the Dash from the lockscreen. If I understand your request correctly, you should be able to use the **Double Tap** action in the same section. I am just unsure of what the view bar is. Hopefully this helps.
